"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type LanguageCode = "en" | "hi" | "mr" | "te";

export interface LanguageOption {
  code: LanguageCode;
  name: string;
  nativeName: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "hi", name: "Hindi", nativeName: "हिंदी" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
];

// Reusable dictionary for UI labels & actions across all 12 user modules.
// Crucial: Technical terms (IS numbers, BIS, QCO, HUID, clauses, scheme names) remain stable and untranslated.
const DICTIONARY: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Navigation & Global
    portalTitle: "MANAK SAARTHI",
    nationalQuality: "National Quality Infrastructure",
    dashboardMode: "Dashboard Mode",
    home: "Home",
    assistant: "AI Assistant",
    findStandard: "Find Standard",
    standards: "Standards",
    qcos: "QCOs",
    certification: "Certification",
    labs: "Labs",
    documents: "Document Analyzer",
    compliance: "Compliance Checker",
    readiness: "Application Readiness",
    compare: "Compare Standards",
    updates: "Updates & Alerts",
    dashboard: "My Dashboard",
    more: "More",
    searchPlaceholder: "Search Indian Standards, QCOs, or enter query...",
    signIn: "Sign In",
    signOut: "Log Out",
    sourceGrounded: "SOURCE-GROUNDED AI",
    realTimeVerification: "Real-time Verification",
    officialSource: "Official BIS Source",
    clause: "Clause",
    verifiedOn: "Last Verified",
    confidence: "Confidence",
    confidenceHigh: "High Confidence",
    confidenceMed: "Medium Confidence",
    confidenceLow: "Requires Verification",
    exploreNow: "Explore Now",
    viewDetails: "View Details",
    disclaimerLegal: "AI-assisted guidance. Official certification, testing, and compliance decisions remain with the Bureau of Indian Standards.",
    evidenceFound: "Evidence Found",
    missingEvidence: "Missing Evidence",
    manualVerification: "Manual Verification Required",
    backToHome: "Return to Home",
    reset: "Reset",
    search: "Search",
    proceed: "Proceed",
    copy: "Copy",
    copied: "Copied",
    officialRecord: "Official BIS Record",
    allCategories: "All Categories",
    allStates: "All States",
    allDomains: "All Domains",

    // Admin Panel Translations
    adminDashboard: "Admin Dashboard",
    adminBrand: "BIS GUIDANCE",
    welcomeBack: "WELCOME BACK,",
    welcomeHeading: "Here’s what’s happening with BIS Guidance today.",
    welcomeSubtext: "Key statistics and recent activity across the platform.",
    quickActions: "Quick Actions",
    totalStandards: "Total Standards",
    activeQcos: "Active QCOs",
    certificationSchemes: "Certification Schemes",
    recognizedLabs: "Recognized Labs",
    recentActivity: "Recent Activity",
    topQueries: "Top Queries",
    viewAll: "View all →",
    addNewStandard: "Add New Standard",
    createQco: "Create QCO",
    addCertScheme: "Add Certification Scheme",
    registerLab: "Register Lab",
    searchAdminPlaceholder: "Search standards, QCOs, certifications...",
    systemOnline: "System Online",
    adminSection: "ADMIN",
    userManagement: "User Management",
    systemLogs: "System Logs",
    settings: "Settings",
    thisMonth: "this month",
    adminProfile: "Admin",
    cancel: "Cancel",
    saveRecord: "Save Record",
    actions: "Actions",
    noRecordsFound: "No records found",
    noRecordsMsg: "There are no entries matching your search criteria.",
    showing: "Showing",
    to: "to",
    of: "of",
    entries: "entries",
    filterRecords: "Filter records...",
    actNewStandard: "New Indian Standard Added",
    actQcoUpdated: "QCO Updated",
    actNewScheme: "New Certification Scheme",
    actNewLab: "New Lab Registered",
    query1: "BIS certification for mobile chargers",
    query2: "QCO applicability for electrical items",
    query3: "Find BIS recognized labs near me",
    query4: "IS standards for food packaging",
    query5: "Harmful substances in toys (QCO)",

    // Inner Admin Pages (English)
    stdPageTitle: "Indian Standards Directory",
    stdPageDesc: "Manage verified Indian Standards (IS), clause index, and technical specifications across sectors.",
    addNewStandardBtn: "Add New Standard",
    searchByIsOrTitle: "Search by IS number or title...",
    allSectors: "All Sectors",
    allStatuses: "All Statuses",
    colIsNumber: "IS NUMBER",
    colStdTitleScope: "STANDARD TITLE & SCOPE",
    colSector: "SECTOR",
    colStatus: "STATUS",
    colLastRevised: "LAST REVISED",
    techClauses: "Technical Clauses",

    qcoPageTitle: "Quality Control Orders (QCOs)",
    qcoPageDesc: "Monitor statutory gazette notifications, compulsory certification mandates, and Ministry enforcement dates.",
    createQcoBtn: "Create QCO Order",
    searchQcoPlaceholder: "Search QCO code, title, or ministry...",
    allMandateStatuses: "All Mandate Statuses",
    colQcoRef: "QCO REFERENCE",
    colQcoSubject: "QCO SUBJECT & SCOPE",
    colNotifiedDate: "NOTIFIED DATE",
    colEnforcementDate: "ENFORCEMENT DATE",
    colMandateStatus: "MANDATE STATUS",

    certPageTitle: "Statutory Certification Schemes",
    certPageDesc: "Configure BIS conformity assessment lifecycle frameworks, factory surveillance rules, and product licensing guidelines.",
    addSchemeBtn: "Add Scheme Framework",
    searchCertPlaceholder: "Search certification schemes...",
    colSchemeCode: "SCHEME CODE",
    colConformityScheme: "CONFORMITY ASSESSMENT SCHEME",
    colMappedStandards: "MAPPED STANDARDS",
    colSurveillanceRule: "AUDIT / SURVEILLANCE RULE",
    colOpStatus: "OPERATIONAL STATUS",

    labPageTitle: "BIS-Recognized Laboratories",
    labPageDesc: "Manage accredited testing facilities, NABL alignment, and recognized laboratory testing scopes.",
    registerLabBtn: "Register Laboratory",
    searchLabPlaceholder: "Search lab name, location, or standards...",
    colLabCode: "LAB CODE",
    colLabNameLoc: "LABORATORY NAME & LOCATION",
    colTestingScope: "RECOGNIZED TESTING SCOPE",
    colValidity: "RECOGNITION VALIDITY",

    docPageTitle: "Document Repository & Gazette Index",
    docPageDesc: "Upload official BIS gazette notifications, standard documents, and test protocol manuals for AI index extraction.",
    uploadGazetteBtn: "Upload Gazette / PDF",
    searchDocPlaceholder: "Search document name or category...",
    colFileName: "DOCUMENT FILE NAME",
    colCategory: "CATEGORY",
    colFileSize: "FILE SIZE",
    colIndexedStandards: "INDEXED STANDARDS",
    colUploadedDate: "UPLOADED DATE",

    usrPageTitle: "User Management & Access Control",
    usrPageDesc: "Manage system administrator privileges, ministry nodal accounts, and lab auditor permissions.",
    provisionUserBtn: "Provision New User",
    searchUserPlaceholder: "Search user name, email, or department...",
    allUserRoles: "All User Roles",
    colUserProfile: "USER PROFILE & EMAIL",
    colAccessRole: "ACCESS ROLE",
    colOrgDept: "ORGANIZATION / DEPARTMENT",
    colLastActive: "LAST ACTIVE",
    colAccountStatus: "ACCOUNT STATUS",

    logPageTitle: "System Audit Logs & Security Trail",
    logPageDesc: "Immutable record of administrative actions, QCO gazette edits, security events, and AI index synchronization.",
    exportLogBtn: "Export Audit Log (CSV)",
    searchLogPlaceholder: "Search audit events, actors, or target resources...",
    allSeverities: "All Severities",
    colTimestamp: "TIMESTAMP",
    colActorSystem: "ACTOR / SYSTEM",
    colEventAction: "EVENT ACTION",
    colTargetResource: "TARGET RESOURCE",
    colSeverity: "SEVERITY",

    setPageTitle: "System & Platform Settings",
    setPageDesc: "Configure admin profile credentials, AI vector index grounding parameters, and security policies.",
    tabAccount: "Account Profile",
    tabPlatform: "Platform & AI Grounding",
    tabSecurity: "Security & Access",
    tabNotifications: "Notifications & Alerts",
    saveSettingsBtn: "Save Settings",

    statusActive: "Active",
    statusUnderReview: "Under Review",
    statusDraft: "Draft",
    statusEnforced: "Enforced",
    statusRecognized: "Recognized",
    statusSuspended: "Suspended",

    edit: "Edit",
    delete: "Delete",
    sectorMechanical: "Mechanical",
    sectorElectronics: "Electronics",
    sectorElectrical: "Electrical",
    sectorConsumerGoods: "Consumer Goods",
    sectorLighting: "Lighting",
    sectorTelecom: "Telecom",

    stdTitle1: "Safety requirements for industrial pumps and liquid handling",
    stdTitle2: "Information Technology Equipment — Safety Requirements",
    stdTitle3: "Safety of Toys — Mechanical and Physical Properties",
    stdTitle4: "Polyvinyl Chloride Insulated Cables for Working Voltages up to 1100V",
    stdTitle5: "Safety of Lamp Controlgear — AC or DC Supplied Electronic Controlgear for LED",
    stdTitle6: "Mobile Phone Handsets — Indian Language Support Requirements",

    qcoTitle1: "Electrical Equipment (Quality Control) Amendment Order, 2025",
    qcoTitle2: "Toys (Quality Control) Order, 2024 Mandate",
    qcoTitle3: "Solar PV Systems and Component Quality Order",
    qcoTitle4: "Chemicals & Petrochemicals (Quality Control) Mandate",
    qcoMin1: "DPIIT / Ministry of Heavy Industries",
    qcoMin2: "Ministry of Commerce & Industry",
    qcoMin3: "Ministry of New & Renewable Energy",
    qcoMin4: "Department of Chemicals & Petrochemicals",

    schName1: "Product Certification Scheme (ISI Mark)",
    schName2: "Compulsory Registration Scheme (CRS)",
    schName3: "Foreign Manufacturers Certification Scheme (FMCS)",
    schName4: "Hallmarking of Precious Metals (HUID)",
    schAudience1: "Domestic Manufacturers & Factories",
    schAudience2: "Electronics & IT Goods Manufacturers",
    schAudience3: "Overseas Exporters to India",
    schAudience4: "Jewellers & Hallmarking Centers",
    schRule1: "Annual Audit & Market Sampling",
    schRule2: "Self-Declaration with Lab Test",
    schRule3: "Pre-Licence Foreign Factory Inspection",
    schRule4: "Real-time Portal Audit & Sampling",

    labName1: "Thermo Test Labs Private Limited",
    labName2: "National Testing House (NTH)",
    labName3: "Apex Precision Calibration & Test Facility",
    labName4: "Sun Energy PV Test Center",
    labScope1: "Pumps, Motors & Industrial Cables (IS 17431, IS 694)",
    labScope2: "Electronics, IT Devices & Batteries (IS 13252)",
    labScope3: "Toy Safety, Chemical Analysis (IS 9873)",
    labScope4: "Solar Modules & Inverters (IS 14286)",

    docCatQco: "QCO Notification",
    docCatStd: "Standard Gazette",
    docCatTest: "Testing Protocol",
    docCited: "Cited",

    roleAdmin: "System Administrator",
    roleNodal: "Ministry Nodal Officer",
    roleLabAdmin: "Lab Administrator",
    roleAuditor: "Standards Auditor",

    logAct1: "Gazette Standard Published",
    logAct2: "Automated Vector Index Sync",
    logAct3: "QCO Enforcement Date Updated",
    logAct4: "Failed Auth Attempt",

    displayName: "Display Name",
    officialEmail: "Official Email",
    adminProfileTitle: "Administrator Profile",
    settingsUpdatedMsg: "Settings updated successfully!",
    deptDivision: "Department / Division",
    timezoneLabel: "Timezone",
    userRoleLabel: "Role Privilege",
    aiGroundingModel: "AI Grounding Model",
    confidenceThreshold: "Confidence Threshold",
    autoIndexPdf: "Auto-Index Gazette PDFs",
    maxCitations: "Max Citations Per Query",
    enable2FA: "Two-Factor Authentication (2FA)",
    sessionTimeout: "Session Timeout",
    ipRestriction: "IP Access Restriction",
    qcoAlerts: "QCO Gazette Email Alerts",
    securityAlerts: "Security & Login Alerts",
    labExpiryAlerts: "Lab Renewal Expiry Alerts",

    // AI Assistant Page
    asstTitle: "Source-Grounded",
    asstItalic: "AI Assistant",
    asstSubtitle: "Interact directly with our verified Indian Standards knowledge index. Get source-backed references, clause citations, and immediate next compliance actions.",
    asstSession: "Real-time Grounded Session",
    asstSessionSub: "Verified BIS Gazettes & IS Codes",
    asstWelcome: "Namaste! I am your MANAK SAARTHI AI Assistant. I provide source-grounded guidance on Indian Standards (IS), Quality Control Orders (QCOs), testing protocols, and BIS certification schemes. How can I assist your compliance journey today?",
    asstWorkflowSteps: "Recommended Next Workflow Steps:",
    asstSourcesTitle: "Verified Data Sources",
    asstSourcesDesc: "Every response from MANAK SAARTHI is indexed against verified institutional data published by the Bureau of Indian Standards and Central Ministries.",
    asstJumpTitle: "Jump to Dedicated Modules",
    asstAdvisoryNotice: "This AI assistant provides informational guidance only. Official test reports, licence grants, and statutory compliance determinations are exclusively issued by authorized officers of the Bureau of Indian Standards.",
    asstAskPlaceholder: "Ask about an Indian Standard, product, QCO mandate, or testing rule...",

    // Find My Standard Page
    findTitle: "Find My",
    findItalic: "Standard",
    findSubtitle: "Convert your natural-language product description, composition, and intended application into potentially applicable Indian Standards and QCO requirements.",
    findTryPreset: "Try a sample manufacturing scenario:",
    findProfileTitle: "Product Profile",
    findProdName: "Product Name / Title *",
    findProdDesc: "Detailed Product Description",
    findMaterial: "Primary Material",
    findIndustry: "Industry Sector",
    findIntendedUse: "Intended Application / Target Consumer",
    findBtn: "Discover Applicable Standards",
    findSearching: "Searching Indian Standards Directory...",
    findResultsTitle: "Potentially Relevant Indian Standards",
    findResultsFor: "Evaluated for",
    findScopeAssessment: "Scope Assessment:",
    findKeySpecs: "Key Tested Specifications:",
    findNotice: "Notice: Identification of applicable standards is based on preliminary product description matching. Official determination of standard applicability should be verified with the concerned technical department at BIS headquarters or regional offices.",

    // Document Analyzer Page
    docTitle: "Document",
    docItalic: "Analyzer",
    docSubtitle: "Upload and analyze BIS Quality Control Orders, laboratory test reports, and standard gazettes. AI automatically extracts cited standards, clauses, and enforcement timelines.",
    docSampleSelector: "Load an official sample document to analyze:",
    docUploadTitle: "Upload BIS Document",
    docUploadDesc: "Drag & drop QCO notification, NABL test report, or standard excerpt (PDF, DOCX up to 25MB)",
    docSelectFile: "Select Local File",
    docClassTitle: "Document Classification",
    docTimelinesTitle: "Critical Timelines & Dates",
    docExtractedTitle: "Identified Indian Standards",
    docReqTitle: "Requirements Identified",
    docMissingTitle: "Potential Missing Information",
    docInquireTitle: "Inquire About This Document",
    docInquirePlaceholder: "Ask a specific question about clauses, testing, or enforcement...",
    docInquireBtn: "Inquire",

    // Certification Navigator Page
    certTitle: "Certification",
    certItalic: "Navigator",
    certSubtitle: "Understand statutory BIS certification schemes, document readiness prerequisites, testing requirements, and step-by-step procedural lifecycles.",
    certAdvisoryNotice: "Procedural Guidance Notice: This navigator provides educational guidance on BIS conformity assessment schemes. Official licence applications must be filed through the official BIS portals (Manakonline / CRS Portal). Final decisions on certification and testing remain exclusively with BIS.",
    certViewFlow: "View Scheme Flow",
    certTimelineTitle: "Procedural Lifecycle & Milestone Timeline",
    certDossierTitle: "Prerequisite Documentation Dossier",
    certDossierDesc: "Before initiating official filing on the BIS portal, manufacturers must assemble and authenticate the following dossier:",
    certTestingTitle: "Testing & Laboratory Protocol",
    certAuditTitle: "Factory Quality Audit & Surveillance",
    certStatutoryRef: "Official Statutory Reference",

    // My Dashboard Page
    dashTitle: "Manufacturer",
    dashItalic: "Dashboard",
    dashSubtitle: "Monitor saved Indian Standards, tracked products, document audit checklists, and testing laboratory pipelines across your manufacturing portfolio.",
    dashTrackNew: "Track New Product",
    dashVerifiedEntity: "Verified Entity",
    dashTrackedCount: "Active Tracked Standards",
    dashPortfolioAvg: "Portfolio Readiness",
    dashSavedStandards: "Saved Indian Standards",
    dashMonitoredProds: "Monitored Manufacturing Products",
    dashRecentSearches: "Recent AI Inquiries & Search History",
    dashReadinessCard: "Overall Compliance Readiness",
    dashAlertsCard: "Monitored Alerts",
    dashShortcuts: "Direct Module Access",

    // Standards Explorer Page
    stdTitle: "Standards",
    stdItalic: "Explorer",
    stdSubtitle: "Search, inspect, and verify published Indian Standards (IS), gazetted amendments, applicable certification schemes, and testing network scope.",
    stdPlaceholder: "Search by IS number (e.g. IS 302, IS 16046), product keyword, or application...",
    stdMandatoryOnly: "Mandatory QCO Only",
    stdShowingCount: "Showing Standards matching query",
    stdKnowStandard: "Know Your Standard (Full Details)",
    stdScopeApplication: "Scope & Application",
    stdAmendmentsStatus: "Amendments Status",
    stdStiStatus: "Testing Scheme (STI)",

    // Compliance Checker Page
    compTitle: "Compliance",
    compItalic: "Checker",
    compSubtitle: "Cross-evaluate uploaded test reports and factory records against mandatory clauses of Indian Standards. Identify supported parameters and highlighted evidence gaps.",
    compNotice: "AI-Assisted Assessment Notice: Based on the information provided, the following requirements appear to be supported. This evaluation does NOT constitute a legal certification or statutory compliance determination. Formal conformity certificates are granted solely by authorized BIS assessing officers following physical audit and designated laboratory testing.",
    compAuditedStd: "Audited Standard",
    compFilterClauses: "Filter Clauses:",
    compParamCol: "Clause / Parameter",
    compSpecCol: "Standard Specification",
    compStatusCol: "Evaluation Status",
    compNotesCol: "Evidence & Audit Notes",

    // Application Readiness Page
    readTitle: "Application",
    readItalic: "Readiness",
    readSubtitle: "Self-evaluate manufacturing premises, laboratory calibration, and documentation completeness before formally submitting your BIS licence or CRS filing.",
    readNotice: "Important Guideline on Readiness Score: This percentage represents an internal readiness self-assessment based on standard BIS application checklists. It is NOT a BIS approval score and does not guarantee licence grant. Final granting of standard mark licences is subject to physical verification and official scrutiny by BIS officers.",
    readConsolidated: "Consolidated Readiness Indicator",
    readAdvancedStage: "Advanced Stage",
    readSatisfiedCount: "checklist parameters satisfied",
    readPriorityNext: "Recommended Next Action Items",

    // BIS Lab Finder Page
    labTitle: "BIS Recognized",
    labItalic: "Lab Finder",
    labSubtitle: "Locate Central, Regional, and NABL-accredited BIS testing laboratories authorized to evaluate your product against mandatory Indian Standards.",
    labPlaceholder: "Search by standard (e.g. IS 302), city, test parameter, or laboratory name...",
    labListMode: "List",
    labMapMode: "Map",
    labShowingCount: "BIS-Recognized Testing Facilities",
    labScopeTitle: "Accredited Testing Scope:",
    labContactBtn: "Contact Lab",
    labMapTitle: "Geographic Testing Network Map",
    labSendQuery: "Send Testing Query",

    // Compare Standards Page
    compareTitle: "Compare",
    compareItalic: "Standards",
    compareSubtitle: "Side-by-side technical evaluation between two Indian Standards. Analyze variations across product scope, testing protocols, mandatory schemes, and gazette mandates.",
    compareSelectPair: "Select Comparison Pair:",
    compareDimCol: "Comparison Dimension",
    compareScope: "Scope & Purpose",
    compareCoverage: "Product Coverage",
    compareTechReq: "Prescribed Technical Requirements",
    compareTests: "Critical Test Methods",
    compareMarking: "Standard Marking Rules",
    compareScheme: "Certification Scheme & Mandate",

    // Updates & Alerts Page
    upTitle: "Updates &",
    upItalic: "Alerts",
    upSubtitle: "Monitor gazetted Quality Control Orders, standard amendments, committee revisions, and testing network updates relevant to your tracked portfolio.",
    upNotice: "Tracking Notice: MANAK SAARTHI indexes published notifications from the official Gazette of India and BIS portal. This feed provides periodic regulatory updates and does not claim real-time continuous surveillance of unpublished draft proceedings.",
    upUnreadOnly: "Unread Only",
    upMarkAllRead: "Mark All Read",
    upTimeline: "Enforcement Timeline:",
    upViewSource: "View Gazette Source",

    // Common Badges, Descriptions & Extra Labels
    asstBadge: "Bureau of Indian Standards • Conversational Guidance",
    stdCatalog: "BIS Standards Catalog",
    accreditedLabs: "Accredited Testing Labs",
    findStandardDesc: "Describe your product in natural language",
    certDesc: "Step-by-step ISI, CRS, and FMCS schemes",
    labDesc: "Locate state & regional test facilities",
    advisoryNotice: "Advisory Notice",
    findBadge: "Discovery Module • Know Your Standard",
    docBadge: "Interpretation Module • Source-Grounded Document AI",
    certBadge: "Guidance Module • Conformity Assessment Framework",
    dashBadge: "Portfolio Manager • Enterprise Compliance",
    stdBadge: "National Catalog • Know Your Standard",
    compBadge: "Verification Module • Diagnostic Audit",
    readBadge: "Self-Assessment Module • Filing Readiness",
    labBadge: "Infrastructure Network • NABL & BIS Laboratories",
    compareBadge: "Analytical Module • Technical Harmonization",
    upBadge: "Regulatory Feed • Official Gazette Surveillance",
    heroTitle: "Empowering Quality,",
    heroItalic: "Inspiring Trust",
    heroSubtitle: "Your single intelligent gateway to Indian Standards, conformity assessment, and laboratory ecosystems across all industrial sectors.",
    heroExplore: "Explore Services",
    heroAskAssistant: "AI Assistant Guidance",
    trusted: "Trusted",
    transparent: "Transparent",
    together: "Together",

    // Landing Page & Home Dashboard
    publicPortalBanner: "Public Portal • Bureau of Indian Standards",
    instantDemoLogin: "Instant Demo Login (Dashboard View)",
    returnToPublic: "← Return to Public Landing Page",
    heroCard1Text: "Products in the market meet BIS standards for your safety.",
    heroCard2Text: "Businesses and consumers trusted BIS across India.",
    heroCard3Text: "Average customer rating for our services.",
    heroExploreBtn: "Explore Our Services",
    featMissionTag: "National Quality Infrastructure",
    featMissionTitle: "Built for Transparency, Compliance & Safety.",
    featMissionSub: "BIS Guidance simplifies standard verification for manufacturers, importers, lab officers, and Indian consumers.",
    featPillar1Title: "Mandatory Safety Standards",
    featPillar1Desc: "Instant lookup of Indian Standards (IS) published by the Bureau of Indian Standards for domestic & imported goods.",
    featPillar2Title: "Quality Control Orders (QCOs)",
    featPillar2Desc: "Track gazette notifications and enforcement timelines for mandatory certification across 700+ product categories.",
    featPillar3Title: "Recognized Testing Network",
    featPillar3Desc: "Locate NABL-accredited BIS testing & calibration labs across all Indian states and regional branches.",
    featCatalogTag: "Frequently Verified",
    featCatalogTitle: "Popular Indian Standards Directory",
    featExploreAll: "Explore All 20,000+ Standards",
    featStat1: "Market Product Safety Compliance",
    featStat2: "Businesses & Consumers Served",
    featStat3: "BIS-Recognized Testing Labs",
    featStat4: "Quality Control Mandates (QCOs)",
    featCtaTitle: "Ready to verify your product compliance?",
    featCtaSub: "Sign in to access your customized dashboard, query real-time Indian Standards, and track certification schemes.",
    featCtaSignIn: "Sign In to Portal",
    featCtaExplore: "Explore AI Guidance",
    aiSearchTag: "Indian Standards • Verified Sources • Real Answers",
    aiSearchTitle: "Navigate Indian Standards,",
    aiSearchItalic: "with confidence.",
    aiSearchSub: "Get accurate, source-grounded information on Indian Standards, Quality Control Orders, certification schemes, and BIS-recognized labs — all in one place.",
    aiSearchPlaceholder: "Ask a question about a product, standard or requirement...",
    aiSearchPopularTopics: "Popular guidance topics:",
    catSectionTitle: "Explore by category",
    catSectionSub: "Browse official standards, mandates, testing networks, and certification pathways.",
    catViewAll: "View all",
    catStdDesc: "Search and view the latest Indian Standards (IS).",
    catQcoDesc: "Find applicable Quality Control Orders for your product.",
    catCertDesc: "Learn about ISI, CRS, FMCS and more.",
    catLabDesc: "Locate accredited testing and calibration labs.",
    catDocDesc: "Guides, forms, notices and circulars.",
    footerTagline: "Standards • Compliance • Confidence",
    footerMinistry: "Department of Consumer Affairs (DoCA) • Ministry of Consumer Affairs, Food & Public Distribution",
    footerCopyright: "© 2026 MANAK SAARTHI • Built for National Quality Infrastructure.",
    footerLinkStandards: "Standards Directory",
    footerLinkAlerts: "Gazette Alerts",
    footerLinkLabs: "Testing Laboratories",
    footerLinkAssistant: "AI Guidance",
  },
  hi: {
    // Navigation & Global
    portalTitle: "मानक सारथी",
    nationalQuality: "राष्ट्रीय गुणवत्ता अवसंरचना",
    dashboardMode: "डैशबोर्ड मोड",
    home: "होम",
    assistant: "एआई सहायक",
    findStandard: "मानक खोजें",
    standards: "मानक",
    qcos: "QCO आदेश",
    certification: "प्रमाणन",
    labs: "प्रयोगशालाएं",
    documents: "दस्तावेज़ विश्लेषक",
    compliance: "अनुपालन परीक्षक",
    readiness: "आवेदन तत्परता",
    compare: "मानक तुलना",
    updates: "अपडेट और अलर्ट",
    dashboard: "डैशबोर्ड",
    more: "अन्य",
    searchPlaceholder: "भारतीय मानक, QCO खोजें या प्रश्न लिखें...",
    signIn: "साइन इन करें",
    signOut: "लॉग आउट",
    sourceGrounded: "स्रोत-आधारित एआई",
    realTimeVerification: "सत्यापित स्रोत",
    officialSource: "आधिकारिक बीआईएस स्रोत",
    clause: "खंड (Clause)",
    verifiedOn: "सत्यापन तिथि",
    confidence: "विश्वसनीयता",
    confidenceHigh: "उच्च विश्वसनीयता",
    confidenceMed: "मध्यम विश्वसनीयता",
    confidenceLow: "सत्यापन आवश्यक",
    exploreNow: "अभी एक्सप्लोर करें",
    viewDetails: "विवरण देखें",
    disclaimerLegal: "एआई-सहायता प्राप्त मार्गदर्शन। आधिकारिक प्रमाणन एवं परीक्षण निर्णय केवल भारतीय मानक ब्यूरो (BIS) द्वारा मान्य हैं।",
    evidenceFound: "प्रमाण उपलब्ध",
    missingEvidence: "प्रमाण अनुपलब्ध",
    manualVerification: "मैन्युअल सत्यापन आवश्यक",
    backToHome: "होम पर लौटें",
    reset: "रीसेट करें",
    search: "खोजें",
    proceed: "आगे बढ़ें",
    copy: "कॉपी करें",
    copied: "कॉपी किया गया",
    officialRecord: "आधिकारिक बीआईएस रिकॉर्ड",
    allCategories: "सभी श्रेणियां",
    allStates: "सभी राज्य",
    allDomains: "सभी डोमेन",

    // Admin Panel Translations (Hindi)
    adminDashboard: "एडमिन डैशबोर्ड",
    adminBrand: "बीआईएस मार्गदर्शन",
    welcomeBack: "पुनः स्वागत है,",
    welcomeHeading: "आज बीआईएस मार्गदर्शन में क्या नया है।",
    welcomeSubtext: "पूरे प्लेटफॉर्म पर मुख्य आंकड़े और हाल की गतिविधियां।",
    quickActions: "त्वरित कार्रवाई",
    totalStandards: "कुल मानक",
    activeQcos: "सक्रिय QCOs",
    certificationSchemes: "प्रमाणन योजनाएं",
    recognizedLabs: "मान्यता प्राप्त लैब",
    recentActivity: "हाल की गतिविधियां",
    topQueries: "शीर्ष प्रश्न",
    viewAll: "सभी देखें →",
    addNewStandard: "नया मानक जोड़ें",
    createQco: "QCO बनाएं",
    addCertScheme: "प्रमाणन योजना जोड़ें",
    registerLab: "लैब पंजीकृत करें",
    searchAdminPlaceholder: "मानक, QCO, प्रमाणन खोजें...",
    systemOnline: "सिस्टम ऑनलाइन",
    adminSection: "प्रशासन",
    userManagement: "उपयोगकर्ता प्रबंधन",
    systemLogs: "सिस्टम लॉग",
    settings: "सेटिंग्स",
    thisMonth: "इस महीने",
    adminProfile: "एडमिन",
    cancel: "रद्द करें",
    saveRecord: "रिकॉर्ड सहेजें",
    actions: "कार्रवाई",
    noRecordsFound: "कोई रिकॉर्ड नहीं मिला",
    noRecordsMsg: "आपकी खोज के अनुसार कोई प्रविष्टि उपलब्ध नहीं है।",
    showing: "दिखाया जा रहा है",
    to: "से",
    of: "का",
    entries: "प्रविष्टियां",
    filterRecords: "रिकॉर्ड फ़िल्टर करें...",
    actNewStandard: "नया भारतीय मानक जोड़ा गया",
    actQcoUpdated: "QCO अद्यतन किया गया",
    actNewScheme: "नई प्रमाणन योजना",
    actNewLab: "नई लैब पंजीकृत की गई",
    query1: "मोबाइल चार्जर के लिए बीआईएस प्रमाणन",
    query2: "विद्युत वस्तुओं के लिए QCO की प्रयोज्यता",
    query3: "मेरे पास मान्यता प्राप्त बीआईएस लैब खोजें",
    query4: "खाद्य पैकेजिंग के लिए भारतीय मानक (IS)",
    query5: "खिलौनों में हानिकारक पदार्थ (QCO)",

    // Inner Admin Pages (Hindi)
    stdPageTitle: "भारतीय मानक निर्देशिका",
    stdPageDesc: "सभी क्षेत्रों में सत्यापित भारतीय मानकों (IS), खंडों और तकनीकी विनिर्देशों का प्रबंधन करें।",
    addNewStandardBtn: "नया मानक जोड़ें",
    searchByIsOrTitle: "आईएस नंबर या शीर्षक खोजें...",
    allSectors: "सभी क्षेत्र",
    allStatuses: "सभी स्थितियां",
    colIsNumber: "आईएस नंबर",
    colStdTitleScope: "मानक शीर्षक एवं दायरा",
    colSector: "क्षेत्र",
    colStatus: "स्थिति",
    colLastRevised: "अंतिम संशोधन",
    techClauses: "तकनीकी खंड",

    qcoPageTitle: "गुणवत्ता नियंत्रण आदेश (QCOs)",
    qcoPageDesc: "वैधानिक राजपत्र अधिसूचनाओं, अनिवार्य प्रमाणन आदेशों और मंत्रालय प्रवर्तन तिथियों की निगरानी करें।",
    createQcoBtn: "QCO आदेश बनाएं",
    searchQcoPlaceholder: "QCO कोड, शीर्षक या मंत्रालय खोजें...",
    allMandateStatuses: "सभी आदेश स्थितियां",
    colQcoRef: "QCO संदर्भ",
    colQcoSubject: "QCO विषय एवं दायरा",
    colNotifiedDate: "अधिसूचना तिथि",
    colEnforcementDate: "प्रवर्तन तिथि",
    colMandateStatus: "आदेश स्थिति",

    certPageTitle: "वैधानिक प्रमाणन योजनाएं",
    certPageDesc: "बीआईएस अनुरूपता मूल्यांकन जीवनचक्र, कारखाना निगरानी नियमों और लाइसेंस दिशानिर्देशों को कॉन्फ़िगर करें।",
    addSchemeBtn: "प्रमाणन योजना जोड़ें",
    searchCertPlaceholder: "प्रमाणन योजनाएं खोजें...",
    colSchemeCode: "योजना कोड",
    colConformityScheme: "अनुरूपता मूल्यांकन योजना",
    colMappedStandards: "मैप किए गए मानक",
    colSurveillanceRule: "ऑडिट / निगरानी नियम",
    colOpStatus: "संचालन स्थिति",

    labPageTitle: "बीआईएस-मान्यता प्राप्त प्रयोगशालाएं",
    labPageDesc: "मान्यता प्राप्त परीक्षण सुविधाओं, NABL संरेखण और प्रयोगशाला परीक्षण दायरे का प्रबंधन करें।",
    registerLabBtn: "प्रयोगशाला पंजीकृत करें",
    searchLabPlaceholder: "लैब का नाम, स्थान या मानक खोजें...",
    colLabCode: "लैब कोड",
    colLabNameLoc: "प्रयोगशाला का नाम एवं स्थान",
    colTestingScope: "मान्यता प्राप्त परीक्षण दायरा",
    colValidity: "मान्यता वैधता",

    docPageTitle: "दस्तावेज़ रिपॉजिटरी एवं राजपत्र अनुक्रमणिका",
    docPageDesc: "एआई इंडेक्स निष्कर्षण के लिए आधिकारिक बीआईएस राजपत्र अधिसूचनाएं और मानक दस्तावेज अपलोड करें।",
    uploadGazetteBtn: "राजपत्र / पीडीएफ अपलोड करें",
    searchDocPlaceholder: "दस्तावेज़ का नाम या श्रेणी खोजें...",
    colFileName: "दस्तावेज़ फ़ाइल नाम",
    colCategory: "श्रेणी",
    colFileSize: "फ़ाइल का आकार",
    colIndexedStandards: "अनुक्रमित मानक",
    colUploadedDate: "अपलोड तिथि",

    usrPageTitle: "उपयोगकर्ता प्रबंधन एवं पहुंच नियंत्रण",
    usrPageDesc: "सिस्टम प्रशासक अधिकारों, मंत्रालय नोडल खातों और लैब लेखापरीक्षक अनुमतियों का प्रबंधन करें।",
    provisionUserBtn: "नया उपयोगकर्ता जोड़ें",
    searchUserPlaceholder: "उपयोगकर्ता नाम, ईमेल या विभाग खोजें...",
    allUserRoles: "सभी उपयोगकर्ता भूमिकाएं",
    colUserProfile: "उपयोगकर्ता प्रोफ़ाइल एवं ईमेल",
    colAccessRole: "पहुंच भूमिका",
    colOrgDept: "संगठन / विभाग",
    colLastActive: "अंतिम सक्रियता",
    colAccountStatus: "खाता स्थिति",

    logPageTitle: "सिस्टम ऑडिट लॉग एवं सुरक्षा रिकॉर्ड",
    logPageDesc: "प्रशासनिक कार्रवाइयों, QCO राजपत्र संपादन, सुरक्षा घटनाओं और एआई सिंक का अपरिवर्तनीय रिकॉर्ड।",
    exportLogBtn: "ऑडिट लॉग निर्यात करें (CSV)",
    searchLogPlaceholder: "ऑडिट घटनाओं, उपयोगकर्ताओं या संसाधनों को खोजें...",
    allSeverities: "सभी गंभीरता स्तर",
    colTimestamp: "समयबद्धता",
    colActorSystem: "उपयोगकर्ता / सिस्टम",
    colEventAction: "घटना कार्रवाई",
    colTargetResource: "लक्ष्य संसाधन",
    colSeverity: "गंभीरता",

    setPageTitle: "सिस्टम एवं प्लेटफॉर्म सेटिंग्स",
    setPageDesc: "प्रशासक क्रेडेंशियल्स, एआई इंडेक्स पैरामीटर और सुरक्षा नीतियों को कॉन्फ़िगर करें।",
    tabAccount: "खाता प्रोफ़ाइल",
    tabPlatform: "प्लेटफ़ॉर्म एवं एआई ग्राइंडिंग",
    tabSecurity: "सुरक्षा एवं पहुंच",
    tabNotifications: "अधिसूचनाएं एवं अलर्ट",
    saveSettingsBtn: "सेटिंग्स सहेजें",

    statusActive: "सक्रिय",
    statusUnderReview: "समीक्षाधीन",
    statusDraft: "प्रारूप",
    statusEnforced: "लागू",
    statusRecognized: "मान्यता प्राप्त",
    statusSuspended: "निलंबित",

    edit: "संपादित करें",
    delete: "हटाएं",
    sectorMechanical: "यांत्रिक",
    sectorElectronics: "इलेक्ट्रॉनिक्स",
    sectorElectrical: "विद्युत",
    sectorConsumerGoods: "उपभोक्ता वस्तुएं",
    sectorLighting: "प्रकाश व्यवस्था",
    sectorTelecom: "दूरसंचार",

    stdTitle1: "औद्योगिक पंपों और द्रव हैंडलिंग के लिए सुरक्षा आवश्यकताएं",
    stdTitle2: "सूचना प्रौद्योगिकी उपकरण — सुरक्षा आवश्यकताएं",
    stdTitle3: "खिलौनों की सुरक्षा — यांत्रिक और भौतिक गुण",
    stdTitle4: "1100V तक के कार्यकारी वोल्टेज के लिए पॉलिविनाइल क्लोराइड इंसुलेटेड केबल",
    stdTitle5: "लैंप कंट्रोलगियर की सुरक्षा — एलईडी के लिए एसी या डीसी आपूर्ति इलेक्ट्रॉनिक्स",
    stdTitle6: "मोबाइल फोन हैंडसेट — भारतीय भाषा सहायता आवश्यकताएं",

    qcoTitle1: "विद्युत उपकरण (गुणवत्ता नियंत्रण) संशोधन आदेश, 2025",
    qcoTitle2: "खिलौने (गुणवत्ता नियंत्रण) आदेश, 2024 जनादेश",
    qcoTitle3: "सौर पीवी सिस्टम और घटक गुणवत्ता आदेश",
    qcoTitle4: "रसायन और पेट्रोकेमिकल्स (गुणवत्ता नियंत्रण) जनादेश",
    qcoMin1: "डीपीआईआईटी / भारी उद्योग मंत्रालय",
    qcoMin2: "वाणिज्य एवं उद्योग मंत्रालय",
    qcoMin3: "नवीन एवं नवीकरणीय ऊर्जा मंत्रालय",
    qcoMin4: "रसायन एवं पेट्रोकेमिकल विभाग",

    schName1: "उत्पाद प्रमाणन योजना (आईएसआई मार्क)",
    schName2: "अनिवार्य पंजीकरण योजना (सीआरएस)",
    schName3: "विदेशी निर्माता प्रमाणन योजना (एफएमसीएस)",
    schName4: "बहुमूल्य धातुओं की हॉलमार्किंग (एचयूआईडी)",
    schAudience1: "घरेलू निर्माता एवं कारखाने",
    schAudience2: "इलेक्ट्रॉनिक्स एवं आईटी सामान निर्माता",
    schAudience3: "भारत में विदेशी निर्यातक",
    schAudience4: "आभूषण निर्माता एवं हॉलमार्किंग केंद्र",
    schRule1: "वार्षिक ऑडिट एवं बाजार नमूनाकरण",
    schRule2: "लैब परीक्षण के साथ स्व-घोषणा",
    schRule3: "लाइसेंस-पूर्व विदेशी कारखाने का निरीक्षण",
    schRule4: "वास्तविक समय पोर्टल ऑडिट एवं नमूनाकरण",

    labName1: "थर्मो टेस्ट लैब्स प्राइवेट लिमिटेड",
    labName2: "राष्ट्रीय परीक्षण गृह (एनटीएच)",
    labName3: "एपेक्स प्रिसिजन कैलिब्रेशन एवं टेस्ट फैसिलिटी",
    labName4: "सन एनर्जी पीवी टेस्ट सेंटर",
    labScope1: "पंप, मोटर एवं औद्योगिक केबल (IS 17431, IS 694)",
    labScope2: "इलेक्ट्रॉनिक्स, आईटी उपकरण एवं बैटरी (IS 13252)",
    labScope3: "खिलौना सुरक्षा, रासायनिक विश्लेषण (IS 9873)",
    labScope4: "सौर मॉड्यूल एवं इनवर्टर (IS 14286)",

    docCatQco: "QCO अधिसूचना",
    docCatStd: "मानक राजपत्र",
    docCatTest: "परीक्षण प्रोटोकॉल",
    docCited: "उद्धृत",

    roleAdmin: "सिस्टम प्रशासक",
    roleNodal: "मंत्रालय नोडल अधिकारी",
    roleLabAdmin: "लैब प्रशासक",
    roleAuditor: "मानक लेखापरीक्षक",

    logAct1: "राजपत्र मानक प्रकाशित",
    logAct2: "स्वचालित वेक्टर इंडेक्स सिंक",
    logAct3: "QCO प्रवर्तन तिथि अद्यतन",
    logAct4: "विफल प्रमाणीकरण प्रयास",

    displayName: "प्रदर्शित नाम",
    officialEmail: "आधिकारिक ईमेल",
    adminProfileTitle: "प्रशासक प्रोफ़ाइल",
    settingsUpdatedMsg: "सेटिंग्स सफलतापूर्वक अद्यतन की गईं!",
    deptDivision: "विभाग / प्रभाग",
    timezoneLabel: "समय क्षेत्र",
    userRoleLabel: "भूमिका विशेषाधिकार",
    aiGroundingModel: "एआई ग्राइंडिंग मॉडल",
    confidenceThreshold: "विश्वसनीयता सीमा",
    autoIndexPdf: "राजपत्र पीडीएफ स्वचालित अनुक्रमणिका",
    maxCitations: "प्रति प्रश्न अधिकतम उद्धरण",
    enable2FA: "द्वि-कारक प्रमाणीकरण (2FA)",
    sessionTimeout: "सत्र समय समाप्ति",
    ipRestriction: "आईपी पहुंच प्रतिबंध",
    qcoAlerts: "QCO राजपत्र ईमेल अलर्ट",
    securityAlerts: "सुरक्षा और लॉगिन अलर्ट",
    labExpiryAlerts: "लैब नवीनीकरण समाप्ति अलर्ट",

    // AI Assistant Page
    asstTitle: "स्रोत-आधारित",
    asstItalic: "एआई सहायक",
    asstSubtitle: "सत्यापित भारतीय मानक ज्ञान सूची के साथ सीधे संवाद करें। आधिकारिक संदर्भ, खंड उद्धरण और तत्काल अनुपालन चरण प्राप्त करें।",
    asstSession: "वास्तविक समय सत्र",
    asstSessionSub: "सत्यापित बीआईएस राजपत्र एवं आईएस कोड",
    asstWelcome: "नमस्ते! मैं आपका मानक सारथी एआई सहायक हूँ। मैं भारतीय मानकों (IS), गुणवत्ता नियंत्रण आदेशों (QCO), परीक्षण नियमों और प्रमाणन योजनाओं पर सत्यापित मार्गदर्शन प्रदान करता हूँ।",
    asstWorkflowSteps: "अनुशंसित अगले अनुपालन चरण:",
    asstSourcesTitle: "सत्यापित डेटा स्रोत",
    asstSourcesDesc: "मानक सारथी का प्रत्येक उत्तर भारतीय मानक ब्यूरो एवं केंद्रीय मंत्रालयों द्वारा प्रकाशित आधिकारिक दस्तावेजों से सत्यापित होता है।",
    asstJumpTitle: "प्रमुख मॉड्यूल पर जाएँ",
    asstAdvisoryNotice: "यह एआई सहायक केवल सूचनात्मक मार्गदर्शन प्रदान करता है। आधिकारिक परीक्षण रिपोर्ट, लाइसेंस स्वीकृति और अनुपालन निर्णय केवल भारतीय मानक ब्यूरो द्वारा अधिकृत अधिकारियों द्वारा ही जारी किए जाते हैं।",
    asstAskPlaceholder: "भारतीय मानक, उत्पाद, QCO आदेश या परीक्षण नियम के बारे में पूछें...",

    // Find My Standard Page
    findTitle: "अपना मानक",
    findItalic: "खोजें",
    findSubtitle: "अपने उत्पाद के विवरण, सामग्री और उपयोग को उपयुक्त भारतीय मानकों और QCO आदेशों में बदलें।",
    findTryPreset: "नमूना निर्माण परिदृश्य आज़माएं:",
    findProfileTitle: "उत्पाद प्रोफ़ाइल",
    findProdName: "उत्पाद का नाम / शीर्षक *",
    findProdDesc: "विस्तृत उत्पाद विवरण",
    findMaterial: "प्राथमिक सामग्री",
    findIndustry: "उद्योग क्षेत्र",
    findIntendedUse: "लक्षित उपयोग / अनुप्रयोग",
    findBtn: "लागू मानकों की खोज करें",
    findSearching: "भारतीय मानक निर्देशिका में खोज जारी है...",
    findResultsTitle: "संभावित रूप से प्रासंगिक भारतीय मानक",
    findResultsFor: "मूल्यांकन उत्पाद:",
    findScopeAssessment: "दायरा मूल्यांकन:",
    findKeySpecs: "प्रमुख परीक्षण विनिर्देश:",
    findNotice: "सूचना: लागू मानकों की पहचान प्रारंभिक विवरण मिलान पर आधारित है। आधिकारिक प्रयोज्यता का सत्यापन बीआईएस तकनीकी विभाग से अवश्य करें।",

    // Document Analyzer Page
    docTitle: "दस्तावेज़",
    docItalic: "विश्लेषक",
    docSubtitle: "बीआईएस गुणवत्ता नियंत्रण आदेश, परीक्षण रिपोर्ट और राजपत्र अपलोड करें। एआई संदर्भित मानकों, खंडों और समयसीमाओं की पहचान करता है।",
    docSampleSelector: "विश्लेषण हेतु आधिकारिक नमूना दस्तावेज़ चुनें:",
    docUploadTitle: "बीआईएस दस्तावेज़ अपलोड करें",
    docUploadDesc: "QCO अधिसूचना, NABL परीक्षण रिपोर्ट या मानक अंश (PDF, DOCX अधिकतम 25MB)",
    docSelectFile: "स्थानीय फ़ाइल चुनें",
    docClassTitle: "दस्तावेज़ वर्गीकरण",
    docTimelinesTitle: "महत्वपूर्ण समयसीमा और तिथियां",
    docExtractedTitle: "पहचाने गए भारतीय मानक",
    docReqTitle: "पहचानी गई आवश्यकताएं",
    docMissingTitle: "संभावित अनुपलब्ध जानकारी",
    docInquireTitle: "इस दस्तावेज़ के बारे में पूछें",
    docInquirePlaceholder: "खंड, परीक्षण या प्रवर्तन के संबंध में प्रश्न पूछें...",
    docInquireBtn: "पूछें",

    // Certification Navigator Page
    certTitle: "प्रमाणन",
    certItalic: "नेविगेटर",
    certSubtitle: "वैधानिक बीआईएस प्रमाणन योजनाओं, आवश्यक दस्तावेज़ों, परीक्षण आवश्यकताओं और चरणबद्ध प्रक्रियाओं को समझें।",
    certAdvisoryNotice: "प्रक्रियात्मक मार्गदर्शन सूचना: यह नेविगेटर केवल शैक्षणिक मार्गदर्शन प्रदान करता है। आधिकारिक आवेदन केवल बीआईएस पोर्टल (Manakonline / CRS Portal) के माध्यम से जमा किए जाने चाहिए।",
    certViewFlow: "योजना प्रवाह देखें",
    certTimelineTitle: "प्रक्रियात्मक जीवनचक्र एवं समयसीमा",
    certDossierTitle: "आवश्यक दस्तावेज़ संचिका",
    certDossierDesc: "बीआईएस पोर्टल पर आधिकारिक आवेदन करने से पहले निर्माताओं को निम्नलिखित दस्तावेज़ तैयार रखने होंगे:",
    certTestingTitle: "परीक्षण एवं प्रयोगशाला प्रोटोकॉल",
    certAuditTitle: "कारखाना गुणवत्ता ऑडिट एवं निरीक्षण",
    certStatutoryRef: "आधिकारिक वैधानिक संदर्भ",

    // My Dashboard Page
    dashTitle: "निर्माता",
    dashItalic: "डैशबोर्ड",
    dashSubtitle: "सहेजे गए भारतीय मानक, ट्रैक किए गए उत्पाद, दस्तावेज़ ऑडिट और प्रयोगशाला परीक्षण पाइपलाइन की निगरानी करें।",
    dashTrackNew: "नया उत्पाद जोड़ें",
    dashVerifiedEntity: "सत्यापित इकाई",
    dashTrackedCount: "सक्रिय ट्रैक किए गए मानक",
    dashPortfolioAvg: "औसत तत्परता",
    dashSavedStandards: "सहेजे गए भारतीय मानक",
    dashMonitoredProds: "निगरानी वाले उत्पाद",
    dashRecentSearches: "हालिया एआई प्रश्न एवं खोज इतिहास",
    dashReadinessCard: "समग्र अनुपालन तत्परता",
    dashAlertsCard: "निगरानी अलर्ट",
    dashShortcuts: "सीधे मॉड्यूल लिंक",

    // Standards Explorer Page
    stdTitle: "मानक",
    stdItalic: "एक्सप्लोरर",
    stdSubtitle: "प्रकाशित भारतीय मानकों (IS), राजपत्रित संशोधनों, प्रमाणन योजनाओं और परीक्षण प्रयोगशालाओं की खोज व सत्यापन करें।",
    stdPlaceholder: "IS संख्या (उदा. IS 302, IS 16046), उत्पाद कीवर्ड या उपयोग लिखें...",
    stdMandatoryOnly: "केवल अनिवार्य QCO",
    stdShowingCount: "खोज से मेल खाते मानक",
    stdKnowStandard: "अपने मानक को जानें (पूर्ण विवरण)",
    stdScopeApplication: "दायरा एवं अनुप्रयोग",
    stdAmendmentsStatus: "संशोधन स्थिति",
    stdStiStatus: "परीक्षण योजना (STI)",

    // Compliance Checker Page
    compTitle: "अनुपालन",
    compItalic: "परीक्षक",
    compSubtitle: "अपलोड की गई परीक्षण रिपोर्ट और फैक्ट्री रिकॉर्ड का भारतीय मानकों के अनिवार्य खंडों के साथ मिलान करें।",
    compNotice: "एआई-सहायता प्राप्त मूल्यांकन सूचना: दी गई जानकारी के आधार पर निम्नलिखित आवश्यकताएं समर्थित प्रतीत होती हैं। यह कानूनी प्रमाणन नहीं है। आधिकारिक प्रमाणन केवल बीआईएस अधिकारियों द्वारा ऑडिट के बाद दिया जाता है।",
    compAuditedStd: "जाँचा गया मानक",
    compFilterClauses: "खंड फ़िल्टर:",
    compParamCol: "खंड / पैरामीटर",
    compSpecCol: "मानक विनिर्देश",
    compStatusCol: "मूल्यांकन स्थिति",
    compNotesCol: "प्रमाण एवं ऑडिट टिप्पणियां",

    // Application Readiness Page
    readTitle: "आवेदन",
    readItalic: "तत्परता",
    readSubtitle: "बीआईएस लाइसेंस या CRS दाखिल करने से पहले विनिर्माण परिसर, प्रयोगशाला अंशांकन और दस्तावेज़ पूर्णता का स्व-मूल्यांकन करें।",
    readNotice: "तत्परता स्कोर पर महत्वपूर्ण दिशानिर्देश: यह प्रतिशत एक आंतरिक स्व-मूल्यांकन है। यह कोई बीआईएस अनुमोदन स्कोर नहीं है और लाइसेंस गारंटी नहीं देता है।",
    readConsolidated: "समेकित तत्परता संकेतक",
    readAdvancedStage: "उन्नत चरण",
    readSatisfiedCount: "जाँच सूची पैरामीटर पूर्ण",
    readPriorityNext: "अनुशंसित प्राथमिकता कार्य",

    // BIS Lab Finder Page
    labTitle: "बीआईएस मान्यता प्राप्त",
    labItalic: "प्रयोगशालाएं",
    labSubtitle: "अनिवार्य भारतीय मानकों के अनुसार आपके उत्पाद का मूल्यांकन करने के लिए अधिकृत केंद्रीय, क्षेत्रीय और NABL प्रयोगशालाएं खोजें।",
    labPlaceholder: "मानक (उदा. IS 302), शहर, परीक्षण पैरामीटर या प्रयोगशाला का नाम लिखें...",
    labListMode: "सूची",
    labMapMode: "मानचित्र",
    labShowingCount: "बीआईएस-मान्यता प्राप्त परीक्षण प्रयोगशालाएं",
    labScopeTitle: "मान्यता प्राप्त परीक्षण दायरा:",
    labContactBtn: "प्रयोगशाला से संपर्क करें",
    labMapTitle: "भौगोलिक परीक्षण नेटवर्क मानचित्र",
    labSendQuery: "परीक्षण पूछताछ भेजें",

    // Compare Standards Page
    compareTitle: "मानक",
    compareItalic: "तुलना",
    compareSubtitle: "दो भारतीय मानकों के बीच तकनीकी तुलना। उत्पाद दायरे, परीक्षण विधियों, प्रमाणन योजनाओं और राजपत्र आदेशों में अंतर का विश्लेषण करें।",
    compareSelectPair: "तुलना युग्म चुनें:",
    compareDimCol: "तुलना आयाम",
    compareScope: "दायरा एवं उद्देश्य",
    compareCoverage: "उत्पाद कवरेज",
    compareTechReq: "निर्धारित तकनीकी आवश्यकताएं",
    compareTests: "महत्वपूर्ण परीक्षण विधियां",
    compareMarking: "मानक अंकन नियम",
    compareScheme: "प्रमाणन योजना एवं जनादेश",

    // Updates & Alerts Page
    upTitle: "अपडेट और",
    upItalic: "अलर्ट",
    upSubtitle: "अपने ट्रैक किए गए पोर्टफोलियो से संबंधित गुणवत्ता नियंत्रण आदेशों (QCO), संशोधनों और परीक्षण नेटवर्क अपडेट पर नज़र रखें।",
    upNotice: "ट्रैकिंग सूचना: मानक सारथी भारत के राजपत्र और बीआईएस पोर्टल से प्रकाशित सूचनाओं को सूचीबद्ध करता है। यह समय-समय पर विनियामक अपडेट प्रदान करता है।",
    upUnreadOnly: "केवल न पढ़े गए",
    upMarkAllRead: "सभी को पढ़ा हुआ चिह्नित करें",
    upTimeline: "प्रवर्तन समयसीमा:",
    upViewSource: "राजपत्र स्रोत देखें",

    // Common Badges, Descriptions & Extra Labels
    asstBadge: "भारतीय मानक ब्यूरो • संवादात्मक मार्गदर्शन",
    stdCatalog: "बीआईएस मानक कैटलॉग",
    accreditedLabs: "मान्यता प्राप्त परीक्षण लैब्स",
    findStandardDesc: "सरल भाषा में अपने उत्पाद का विवरण दें",
    certDesc: "ISI, CRS एवं FMCS योजनाओं की चरणबद्ध प्रक्रिया",
    labDesc: "राज्य एवं क्षेत्रीय परीक्षण प्रयोगशालाएं खोजें",
    advisoryNotice: "सलाहकारी सूचना",
    findBadge: "खोज मॉड्यूल • अपने मानक को जानें",
    docBadge: "विश्लेषण मॉड्यूल • स्रोत-आधारित दस्तावेज़ एआई",
    certBadge: "मार्गदर्शन मॉड्यूल • अनुरूपता मूल्यांकन ढांचा",
    dashBadge: "पोर्टफोलियो प्रबंधक • उद्यम अनुपालन",
    stdBadge: "राष्ट्रीय निर्देशिका • अपने मानक को जानें",
    compBadge: "सत्यापन मॉड्यूल • नैदानिक ऑडिट",
    readBadge: "स्व-मूल्यांकन मॉड्यूल • आवेदन तत्परता",
    labBadge: "अवसंरचना नेटवर्क • NABL और बीआईएस प्रयोगशालाएं",
    compareBadge: "विश्लेषणात्मक मॉड्यूल • तकनीकी तुलना",
    upBadge: "नियामक फ़ीड • आधिकारिक राजपत्र निगरानी",
    heroTitle: "गुणवत्ता का सशक्तिकरण,",
    heroItalic: "विश्वास की प्रेरणा",
    heroSubtitle: "सभी औद्योगिक क्षेत्रों में भारतीय मानकों, अनुरूपता मूल्यांकन और प्रयोगशाला पारिस्थितिकी तंत्र के लिए आपका एकल मार्गदर्शक।",
    heroExplore: "सेवाएं एक्सप्लोर करें",
    heroAskAssistant: "एआई सहायक मार्गदर्शन",
    trusted: "विश्वसनीय",
    transparent: "पारदर्शी",
    together: "सहयोगी",

    // Landing Page & Home Dashboard
    publicPortalBanner: "सार्वजनिक पोर्टल • भारतीय मानक ब्यूरो",
    instantDemoLogin: "त्वरित डेमो लॉगिन (डैशबोर्ड दृश्य)",
    returnToPublic: "← सार्वजनिक होमपेज पर लौटें",
    heroCard1Text: "आपकी सुरक्षा हेतु बाजार में उत्पाद बीआईएस मानकों के अनुरूप हैं।",
    heroCard2Text: "भारत भर में 25 लाख से अधिक व्यवसायों एवं उपभोक्ताओं का भरोसा।",
    heroCard3Text: "हमारी सेवाओं के लिए औसत उपयोगकर्ता संतुष्टि रेटिंग।",
    heroExploreBtn: "हमारी सेवाएं देखें",
    featMissionTag: "राष्ट्रीय गुणवत्ता अवसंरचना",
    featMissionTitle: "पारदर्शिता, अनुपालन एवं सुरक्षा के लिए निर्मित।",
    featMissionSub: "मानक सारथी निर्माताओं, आयातकों, प्रयोगशाला अधिकारियों और भारतीय उपभोक्ताओं के लिए मानक सत्यापन को सरल बनाता है।",
    featPillar1Title: "अनिवार्य सुरक्षा मानक",
    featPillar1Desc: "घरेलू और आयातित वस्तुओं के लिए भारतीय मानक ब्यूरो द्वारा प्रकाशित भारतीय मानकों (IS) की त्वरित खोज।",
    featPillar2Title: "गुणवत्ता नियंत्रण आदेश (QCO)",
    featPillar2Desc: "700+ उत्पाद श्रेणियों में अनिवार्य प्रमाणन के लिए राजपत्र अधिसूचनाओं और प्रवर्तन समयसीमा को ट्रैक करें।",
    featPillar3Title: "मान्यता प्राप्त परीक्षण नेटवर्क",
    featPillar3Desc: "सभी भारतीय राज्यों और क्षेत्रीय शाखाओं में NABL-मान्यता प्राप्त बीआईएस परीक्षण एवं अंशांकन प्रयोगशालाएं खोजें।",
    featCatalogTag: "बार-बार देखे जाने वाले",
    featCatalogTitle: "लोकप्रिय भारतीय मानक निर्देशिका",
    featExploreAll: "सभी 20,000+ मानक देखें",
    featStat1: "बाजार उत्पाद सुरक्षा अनुपालन",
    featStat2: "व्यवसाय एवं उपभोक्ता लाभान्वित",
    featStat3: "बीआईएस-मान्यता प्राप्त परीक्षण लैब्स",
    featStat4: "गुणवत्ता नियंत्रण आदेश (QCOs)",
    featCtaTitle: "क्या आप अपने उत्पाद अनुपालन का सत्यापन करने के लिए तैयार हैं?",
    featCtaSub: "अनुकूलित डैशबोर्ड तक पहुंचने, वास्तविक समय में भारतीय मानकों की जांच करने और प्रमाणन योजनाओं को ट्रैक करने के लिए साइन इन करें।",
    featCtaSignIn: "पोर्टल पर साइन इन करें",
    featCtaExplore: "एआई मार्गदर्शन एक्सप्लोर करें",
    aiSearchTag: "भारतीय मानक • सत्यापित स्रोत • सटीक उत्तर",
    aiSearchTitle: "भारतीय मानकों को समझें,",
    aiSearchItalic: "पूर्ण विश्वास के साथ।",
    aiSearchSub: "भारतीय मानकों, गुणवत्ता नियंत्रण आदेशों, प्रमाणन योजनाओं और बीआईएस प्रयोगशालाओं पर सटीक एवं स्रोत-आधारित जानकारी — एक ही स्थान पर।",
    aiSearchPlaceholder: "किसी उत्पाद, मानक या नियम के बारे में प्रश्न पूछें...",
    aiSearchPopularTopics: "लोकप्रिय मार्गदर्शन विषय:",
    catSectionTitle: "श्रेणी अनुसार अन्वेषण करें",
    catSectionSub: "आधिकारिक मानकों, आदेशों, परीक्षण नेटवर्क और प्रमाणन प्रक्रियाओं को ब्राउज़ करें।",
    catViewAll: "सभी देखें",
    catStdDesc: "नवीनतम भारतीय मानक (IS) खोजें और देखें।",
    catQcoDesc: "अपने उत्पाद के लिए लागू गुणवत्ता नियंत्रण आदेश खोजें।",
    catCertDesc: "ISI, CRS, FMCS और अन्य योजनाओं की जानकारी प्राप्त करें।",
    catLabDesc: "मान्यता प्राप्त परीक्षण और अंशांकन प्रयोगशालाएं खोजें।",
    catDocDesc: "दिशानिर्देश, प्रपत्र, सूचनाएं और परिपत्र।",
    footerTagline: "मानक • अनुपालन • विश्वास",
    footerMinistry: "उपभोक्ता मामले विभाग (DoCA) • उपभोक्ता मामले, खाद्य एवं सार्वजनिक वितरण मंत्रालय",
    footerCopyright: "© 2026 मानक सारथी • राष्ट्रीय गुणवत्ता अवसंरचना हेतु निर्मित।",
    footerLinkStandards: "मानक निर्देशिका",
    footerLinkAlerts: "राजपत्र अलर्ट",
    footerLinkLabs: "परीक्षण प्रयोगशालाएं",
    footerLinkAssistant: "एआई मार्गदर्शन",
  },
  mr: {
    // Navigation & Global
    portalTitle: "मानक सारथी",
    nationalQuality: "राष्ट्रीय गुणवत्ता पायाभूत सुविधा",
    dashboardMode: "डॅशबोर्ड मोड",
    home: "मुख्यपृष्ठ",
    assistant: "एआय सहाय्यक",
    findStandard: "मानक शोधा",
    standards: "मानके",
    qcos: "QCO आदेश",
    certification: "प्रमाणन",
    labs: "प्रयोगशाळा",
    documents: "दस्तऐवज विश्लेषक",
    compliance: "अनुपालन तपासक",
    readiness: "अर्ज तयारी",
    compare: "मानक तुलना",
    updates: "अपडेट्स व अलर्ट्स",
    dashboard: "डॅशबोर्ड",
    more: "इतर",
    searchPlaceholder: "भारतीय मानक, QCO शोधा किंवा प्रश्न टाका...",
    signIn: "साइन इन",
    signOut: "लॉग आउट",
    sourceGrounded: "स्रोत-आधारित एआय",
    realTimeVerification: "तपासलेले स्रोत",
    officialSource: "अधिकृत बीआयएस स्रोत",
    clause: "कलम (Clause)",
    verifiedOn: "पडताळणी तारीख",
    confidence: "विश्वासार्हता",
    confidenceHigh: "उच्च विश्वासार्हता",
    confidenceMed: "मध्यम विश्वासार्हता",
    confidenceLow: "पडताळणी आवश्यक",
    exploreNow: "आत्ताच एक्सप्लोर करा",
    viewDetails: "तपशील पहा",
    disclaimerLegal: "एआय-सहाय्यक मार्गदर्शन. अधिकृत प्रमाणीकरण व चाचणीचे अंतिम निर्णय भारतीय मानक ब्युरो (BIS) कडे आहेत.",
    evidenceFound: "पुरावा सापडला",
    missingEvidence: "पुरावा उपलब्ध नाही",
    manualVerification: "मॅन्युअल पडताळणी आवश्यक",
    backToHome: "मुख्यपृष्ठावर परत जा",
    reset: "रीसेट",
    search: "शोधा",
    proceed: "पुढे चला",
    copy: "कॉपी करा",
    copied: "कॉपी केले",
    officialRecord: "अधिकृत बीआयएस नोंद",
    allCategories: "सर्व श्रेणी",
    allStates: "सर्व राज्ये",
    allDomains: "सर्व क्षेत्रे",

    // Admin Panel Translations (Marathi)
    adminDashboard: "अ‍ॅडमिन डॅशबोर्ड",
    adminBrand: "बीआयएस मार्गदर्शन",
    welcomeBack: "पुन्हा स्वागत आहे,",
    welcomeHeading: "आज बीआयएस मार्गदर्शनामध्ये काय घडत आहे.",
    welcomeSubtext: "संपूर्ण प्लॅटफॉर्मवरील मुख्य आकडेवारी आणि अलीकडील उपक्रम.",
    quickActions: "जलद कृती",
    totalStandards: "एकूण मानके",
    activeQcos: "सक्रिय QCOs",
    certificationSchemes: "प्रमाणन योजना",
    recognizedLabs: "मान्यताप्राप्त प्रयोगशाळा",
    recentActivity: "अलीकडील उपक्रम",
    topQueries: "प्रमुख प्रश्न",
    viewAll: "सर्व पहा →",
    addNewStandard: "नवीन मानक जोडा",
    createQco: "QCO तयार करा",
    addCertScheme: "प्रमाणन योजना जोडा",
    registerLab: "प्रयोगशाळा नोंदवा",
    searchAdminPlaceholder: "मानके, QCO, प्रमाणन शोधा...",
    systemOnline: "सिस्टम ऑनलाईन",
    adminSection: "प्रशासन",
    userManagement: "वापरकर्ता व्यवस्थापन",
    systemLogs: "सिस्टम लॉग्स",
    settings: "सेटिंग्ज",
    thisMonth: "या महिन्यात",
    adminProfile: "अ‍ॅडमिन",
    cancel: "रद्द करा",
    saveRecord: "नोंद जतन करा",
    actions: "कृती",
    noRecordsFound: "कोणतीही नोंद आढळली नाही",
    noRecordsMsg: "तुमच्या शोधाशी जुळणाऱ्या नोंदी उपलब्ध नाहीत.",
    showing: "दर्शवत आहे",
    to: "ते",
    of: "पैकी",
    entries: "नोंदी",
    filterRecords: "नोंदी फिल्टर करा...",
    actNewStandard: "नवीन भारतीय मानक जोडले",
    actQcoUpdated: "QCO अपडेट केले",
    actNewScheme: "नवीन प्रमाणन योजना",
    actNewLab: "नवीन प्रयोगशाळा नोंदवली",
    query1: "मोबाईल चार्जरसाठी बीआयएस प्रमाणीकरण",
    query2: "विद्युत वस्तूंसाठी QCO ची उपयुक्तता",
    query3: "माझ्या जवळील मान्यताप्राप्त बीआयएस प्रयोगशाळा शोधा",
    query4: "अन्न पॅकेजिंगसाठी भारतीय मानके (IS)",
    query5: "खेळण्यांमधील हानिकारक घटक (QCO)",

    // Inner Admin Pages (Marathi)
    stdPageTitle: "भारतीय मानके निर्देशिका",
    stdPageDesc: "सर्व क्षेत्रांमधील सत्यापित भारतीय मानके (IS), कलम आणि तांत्रिक तपशीलांचे व्यवस्थापन करा.",
    addNewStandardBtn: "नवीन मानक जोडा",
    searchByIsOrTitle: "IS क्रमांक किंवा शीर्षक शोधा...",
    allSectors: "सर्व क्षेत्रे",
    allStatuses: "सर्व स्थिती",
    colIsNumber: "IS क्रमांक",
    colStdTitleScope: "मानक शीर्षक आणि व्याप्ती",
    colSector: "क्षेत्र",
    colStatus: "स्थिती",
    colLastRevised: "अंतिम सुधारणा",
    techClauses: "तांत्रिक कलमे",

    qcoPageTitle: "गुणवत्ता नियंत्रण आदेश (QCOs)",
    qcoPageDesc: "वैधानिक राजपत्र सूचना, अनिवार्य प्रमाणन आदेश आणि मंत्रालय अंमलबजावणी तारखांचे निरीक्षण करा.",
    createQcoBtn: "QCO आदेश तयार करा",
    searchQcoPlaceholder: "QCO कोड, शीर्षक किंवा मंत्रालय शोधा...",
    allMandateStatuses: "सर्व आदेश स्थिती",
    colQcoRef: "QCO संदर्भ",
    colQcoSubject: "QCO विषय आणि व्याप्ती",
    colNotifiedDate: "अधिसूचना तारीख",
    colEnforcementDate: "अंमलबजावणी तारीख",
    colMandateStatus: "आदेश स्थिती",

    certPageTitle: "वैधानिक प्रमाणन योजना",
    certPageDesc: "बीआयएस मानकांनुसार तपासणी, कारखाना पाहणी नियम आणि परवाना मार्गदर्शक तत्त्वे सेट करा.",
    addSchemeBtn: "प्रमाणन योजना जोडा",
    searchCertPlaceholder: "प्रमाणन योजना शोधा...",
    colSchemeCode: "योजना कोड",
    colConformityScheme: "अनुरूपता मूल्यमापन योजना",
    colMappedStandards: "मॅप केलेली मानके",
    colSurveillanceRule: "ऑडिट / पाहणी नियम",
    colOpStatus: "कार्यरत स्थिती",

    labPageTitle: "बीआयएस-मान्यताप्राप्त प्रयोगशाळा",
    labPageDesc: "मान्यताप्राप्त चाचणी सुविधा, NABL संरेखन आणि प्रयोगशाळा चाचणी व्याप्तीचे व्यवस्थापन करा.",
    registerLabBtn: "प्रयोगशाळा नोंदवा",
    searchLabPlaceholder: "प्रयोगशाळेचे नाव, ठिकाण किंवा मानके शोधा...",
    colLabCode: "प्रयोगशाळा कोड",
    colLabNameLoc: "प्रयोगशाळेचे नाव आणि ठिकाण",
    colTestingScope: "मान्यताप्राप्त चाचणी व्याप्ती",
    colValidity: "मान्यता वैधता",

    docPageTitle: "दस्तऐवज भांडार व राजपत्र सूची",
    docPageDesc: "एआय अनुक्रमणिका काढण्यासाठी अधिकृत बीआयएस राजपत्र सूचना आणि मानक दस्तऐवज अपलोड करा.",
    uploadGazetteBtn: "राजपत्र / पीडीएफ अपलोड करा",
    searchDocPlaceholder: "दस्तऐवजाचे नाव किंवा वर्गवारी शोधा...",
    colFileName: "दस्तऐवज फाइल नाव",
    colCategory: "वर्गवारी",
    colFileSize: "फाइल आकार",
    colIndexedStandards: "अनुक्रमित मानके",
    colUploadedDate: "अपलोड तारीख",

    usrPageTitle: "वापरकर्ता व्यवस्थापन आणि प्रवेश नियंत्रण",
    usrPageDesc: "सिस्टम प्रशासक हक्क, मंत्रालय नोडल खाती आणि प्रयोगशाळा तपासक परवानग्यांचे व्यवस्थापन करा.",
    provisionUserBtn: "नवीन वापरकर्ता जोडा",
    searchUserPlaceholder: "वापरकर्त्याचे नाव, ईमेल किंवा विभाग शोधा...",
    allUserRoles: "सर्व वापरकर्ता भूमिका",
    colUserProfile: "वापरकर्ता प्रोफाईल आणि ईमेल",
    colAccessRole: "प्रवेश भूमिका",
    colOrgDept: "संस्था / विभाग",
    colLastActive: "अंतिम सक्रियता",
    colAccountStatus: "खाते स्थिती",

    logPageTitle: "सिस्टम ऑडिट लॉग्स व सुरक्षा ट्रेल",
    logPageDesc: "प्रशासकीय कृती, QCO राजपत्र संपादन, सुरक्षा घटना आणि एआय सिंकची कायमस्वरूपी नोंद.",
    exportLogBtn: "ऑडिट लॉग निर्यात करा (CSV)",
    searchLogPlaceholder: "ऑडिट घटना, वापरकर्ते किंवा संसाधने शोधा...",
    allSeverities: "सर्व तीव्रता पातळी",
    colTimestamp: "वेळ",
    colActorSystem: "वापरकर्ता / सिस्टम",
    colEventAction: "घटना कृती",
    colTargetResource: "लक्ष्य संसाधन",
    colSeverity: "तीव्रता",

    setPageTitle: "सिस्टम व प्लॅटफॉर्म सेटिंग्ज",
    setPageDesc: "प्रशासक क्रेडेंशियल्स, एआय इंडेक्स पॅरामीटर्स आणि सुरक्षा धोरणे सेट करा.",
    tabAccount: "खाते प्रोफाईल",
    tabPlatform: "प्लॅटफॉर्म व एआय ग्राइंडिंग",
    tabSecurity: "सुरक्षा व प्रवेश",
    tabNotifications: "सूचना व अलर्ट्स",
    saveSettingsBtn: "सेटिंग्ज जतन करा",

    statusActive: "सक्रिय",
    statusUnderReview: "तपासणीखाली",
    statusDraft: "मसुदा",
    statusEnforced: "लागू",
    statusRecognized: "मान्यताप्राप्त",
    statusSuspended: "निलंबित",

    edit: "संपादीत करा",
    delete: "हटवा",
    sectorMechanical: "यांत्रिक",
    sectorElectronics: "इलेक्ट्रॉनिक्स",
    sectorElectrical: "विद्युत",
    sectorConsumerGoods: "ग्राहक वस्तू",
    sectorLighting: "प्रकाश व्यवस्था",
    sectorTelecom: "दूरसंचार",

    stdTitle1: "औद्योगिक पंप आणि द्रव हाताळणीसाठी सुरक्षा आवश्यकता",
    stdTitle2: "माहिती तंत्रज्ञान उपकरणे — सुरक्षा आवश्यकता",
    stdTitle3: "खेळण्यांची सुरक्षा — यांत्रिक आणि भौतिक गुणधर्म",
    stdTitle4: "1100V पर्यंतच्या कार्यरत व्होल्टेजसाठी पॉलिव्हिनाईल क्लोराईड इन्सुलेटेड केबल्स",
    stdTitle5: "दिवे कंट्रोलगिअरची सुरक्षा — एलईडीसाठी एसी किंवा डीसी इलेक्ट्रॉनिक कंट्रोलगिअर",
    stdTitle6: "मोबाईल फोन हँडसेट — भारतीय भाषा समर्थन आवश्यकता",

    qcoTitle1: "विद्युत उपकरणे (गुणवत्ता नियंत्रण) दुरुस्ती आदेश, २०२५",
    qcoTitle2: "खेळणी (गुणवत्ता नियंत्रण) आदेश, २०२४ जनादेश",
    qcoTitle3: "सौर पीव्ही सिस्टीम आणि घटक गुणवत्ता आदेश",
    qcoTitle4: "रसायने आणि पेट्रोकेमिकल्स (गुणवत्ता नियंत्रण) जनादेश",
    qcoMin1: "डीपीआयआयटी / भारी उद्योग मंत्रालय",
    qcoMin2: "वाणिज्य आणि उद्योग मंत्रालय",
    qcoMin3: "नवीन आणि नवीकरणीय ऊर्जा मंत्रालय",
    qcoMin4: "रसायन आणि पेट्रोकेमिकल विभाग",

    schName1: "उत्पादन प्रमाणन योजना (आयएसआय मार्क)",
    schName2: "अनिवार्य नोंदणी योजना (सीआरएस)",
    schName3: "परदेशी उत्पादक प्रमाणन योजना (एफएमसीएस)",
    schName4: "मौल्यवान धातूंचे हॉलमार्किंग (एचयूआयडी)",
    schAudience1: "स्थानिक उत्पादक आणि कारखाने",
    schAudience2: "इलेक्ट्रॉनिक्स आणि आयटी वस्तू उत्पादक",
    schAudience3: "भारतातील परदेशी निर्यातदार",
    schAudience4: "सुवर्णकार आणि हॉलमार्किंग केंद्रे",
    schRule1: "वार्षिक तपासणी आणि नमुना चाचणी",
    schRule2: "प्रयोगशाळा चाचणीसह स्वयं-घोषणा",
    schRule3: "परवानापूर्व परदेशी कारखान्याची पाहणी",
    schRule4: "रिअल-टाइम पोर्टल ऑडिट आणि नमुने",

    labName1: "थर्मो टेस्ट लॅब्स प्रायव्हेट लिमिटेड",
    labName2: "राष्ट्रीय चाचणी केंद्र (एनटीएच)",
    labName3: "ॲपेक्स प्रिसिजन कॅलिब्रेशन व चाचणी केंद्र",
    labName4: "सन एनर्जी पीव्ही चाचणी केंद्र",
    labScope1: "पंप, मोटर्स आणि औद्योगिक केबल्स (IS 17431, IS 694)",
    labScope2: "इलेक्ट्रॉनिक्स, आयटी उपकरणे आणि बॅटऱ्या (IS 13252)",
    labScope3: "खेळणी सुरक्षा, रासायनिक विश्लेषण (IS 9873)",
    labScope4: "सौर मॉड्यूल आणि इनव्हर्टर (IS 14286)",

    docCatQco: "QCO अधिसूचना",
    docCatStd: "मानक राजपत्र",
    docCatTest: "चाचणी नियम",
    docCited: "संदर्भित",

    roleAdmin: "सिस्टम प्रशासक",
    roleNodal: "मंत्रालय नोडल अधिकारी",
    roleLabAdmin: "प्रयोगशाळा प्रशासक",
    roleAuditor: "मानक तपासक",

    logAct1: "राजपत्र मानक प्रसिद्ध",
    logAct2: "स्वयंचलित वेक्टर इंडेक्स सिंक",
    logAct3: "QCO अंमलबजावणी तारीख अपडेट",
    logAct4: "अपयशी लॉगइन प्रयत्न",

    displayName: "प्रदर्शित नाव",
    officialEmail: "अधिकृत ईमेल",
    adminProfileTitle: "प्रशासक प्रोफाईल",
    settingsUpdatedMsg: "सेटिंग्ज यशस्वीरित्या अपडेट केल्या!",
    deptDivision: "विभाग / प्रभाग",
    timezoneLabel: "वेळ क्षेत्र",
    userRoleLabel: "भूमिका अधिकार",
    aiGroundingModel: "एआय ग्राइंडिंग मॉडेल",
    confidenceThreshold: "विश्वासार्हता मर्यादा",
    autoIndexPdf: "राजपत्र पीडीएफ स्वयंचलित अनुक्रमणिका",
    maxCitations: "प्रत्येक प्रश्नासाठी कमाल संदर्भ",
    enable2FA: "द्वि-घटक प्रमाणीकरण (2FA)",
    sessionTimeout: "सत्र वेळ समाप्ती",
    ipRestriction: "आयपी प्रवेश मर्यादा",
    qcoAlerts: "QCO राजपत्र ईमेल अलर्ट",
    securityAlerts: "सुरक्षा व लॉगइन अलर्ट",
    labExpiryAlerts: "प्रयोगशाळा नूतनीकरण मुदत अलर्ट",

    // AI Assistant Page
    asstTitle: "स्रोत-आधारित",
    asstItalic: "एआय सहाय्यक",
    asstSubtitle: "तपासलेल्या भारतीय मानकांच्या ज्ञानसूचीशी थेट संवाद साधा. अधिकृत संदर्भ, कलम उद्धरणे व तत्काळ अनुपालन पायऱ्या मिळवा.",
    asstSession: "रिअल-टाइम सत्र",
    asstSessionSub: "तपासलेले बीआयएस राजपत्र व आयएस कोड",
    asstWelcome: "नमस्कार! मी आपला मानक सारथी एआय सहाय्यक आहे. मी भारतीय मानके (IS), गुणवत्ता नियंत्रण आदेश (QCO) आणि प्रमाणीकरण योजनांवर मार्गदर्शन करतो.",
    asstWorkflowSteps: "पुढील अनुपालन पायऱ्या:",
    asstSourcesTitle: "सत्यापित डेटा स्रोत",
    asstSourcesDesc: "मानक सारथीचे प्रत्येक उत्तर बीआयएस आणि केंद्रीय मंत्रालयांद्वारे प्रकाशित अधिकृत डेटाशी जोडलेले असते.",
    asstJumpTitle: "प्रमुख विभागांवर जा",
    asstAdvisoryNotice: "हा एआय सहाय्यक केवळ माहितीपर मार्गदर्शन करतो. अंतिम प्रमाणीकरण व चाचणी निर्णय भारतीय मानक ब्युरोच्या अधिकृत अधिकाऱ्यांकडेच असतात.",
    asstAskPlaceholder: "भारतीय मानक, उत्पादन किंवा नियमांबद्दल विचारा...",

    // Find My Standard Page
    findTitle: "आपले मानक",
    findItalic: "शोधा",
    findSubtitle: "आपल्या उत्पादनाचे वर्णन, घटक व उपयोग यावरून लागू होणारी भारतीय मानके व QCO आदेश शोधा.",
    findTryPreset: "उत्पादन परिस्थिती निवडा:",
    findProfileTitle: "उत्पादन प्रोफाइल",
    findProdName: "उत्पादनाचे नाव *",
    findProdDesc: "तपशीलवार वर्णन",
    findMaterial: "प्राथमिक सामग्री",
    findIndustry: "उद्योग क्षेत्र",
    findIntendedUse: "वापर / अनुप्रयोग",
    findBtn: "लागू मानके शोधा",
    findSearching: "भारतीय मानक निर्देशिकेत शोध सुरू आहे...",
    findResultsTitle: "संभाव्य संबंधित भारतीय मानके",
    findResultsFor: "मूल्यांकन उत्पादन:",
    findScopeAssessment: "व्याप्ती मूल्यांकन:",
    findKeySpecs: "प्रमुख चाचणी निकष:",
    findNotice: "सूचना: मानकांची ओळख प्राथमिक वर्णनावर आधारित आहे. अंतिम निश्चिती बीआयएस कार्यालयाशी पडताळून करावी.",

    // Document Analyzer Page
    docTitle: "दस्तऐवज",
    docItalic: "विश्लेषक",
    docSubtitle: "QCO आदेश आणि चाचणी अहवाल अपलोड करा. एआय मानके, कलमे आणि मुदती स्वयंचलितपणे शोधून देईल.",
    docSampleSelector: "विश्लेषणासाठी नमुना दस्तऐवज निवडा:",
    docUploadTitle: "बीआयएस दस्तऐवज अपलोड करा",
    docUploadDesc: "QCO राजपत्र किंवा NABL चाचणी अहवाल (PDF, DOCX कमाल 25MB)",
    docSelectFile: "स्थानिक फाइल निवडा",
    docClassTitle: "दस्तऐवज वर्गीकरण",
    docTimelinesTitle: "महत्त्वाच्या मुदती आणि तारखा",
    docExtractedTitle: "ओळखलेली भारतीय मानके",
    docReqTitle: "ओळखलेल्या आवश्यकता",
    docMissingTitle: "अनुपलब्ध माहिती",
    docInquireTitle: "या दस्तऐवजाबद्दल विचारा",
    docInquirePlaceholder: "कलमे किंवा चाचणीबद्दल विचारा...",
    docInquireBtn: "विचारा",

    // Certification Navigator Page
    certTitle: "प्रमाणीकरण",
    certItalic: "नेव्हिगेटर",
    certSubtitle: "बीआयएस प्रमाणीकरण योजना, आवश्यक कागदपत्रे आणि टप्प्याटप्प्याने प्रक्रिया समजून घ्या.",
    certAdvisoryNotice: "मार्गदर्शन सूचना: हा नेव्हिगेटर शैक्षणिक मार्गदर्शन प्रदान करतो. अधिकृत अर्ज बीआयएस पोर्टलवरच केले पाहिजेत.",
    certViewFlow: "योजना प्रवाह पहा",
    certTimelineTitle: "प्रक्रियात्मक जीवनचक्र व टप्पे",
    certDossierTitle: "आवश्यक कागदपत्रे संचिका",
    certDossierDesc: "बीआयएस पोर्टलवर अधिकृत अर्ज करण्यापूर्वी उत्पादकांनी खालील कागदपत्रे तयार ठेवावीत:",
    certTestingTitle: "चाचणी व प्रयोगशाळा नियम",
    certAuditTitle: "कारखाना गुणवत्ता तपासणी",
    certStatutoryRef: "अधिकृत वैधानिक संदर्भ",

    // My Dashboard Page
    dashTitle: "उत्पादक",
    dashItalic: "डॅशबोर्ड",
    dashSubtitle: "जतन केलेली मानके, उत्पादने, तपासणी यादी आणि चाचणी प्रयोगशाळांची एकाच ठिकाणी देखरेख करा.",
    dashTrackNew: "नवीन उत्पादन जोडा",
    dashVerifiedEntity: "सत्यापित संस्था",
    dashTrackedCount: "सक्रिय मानके",
    dashPortfolioAvg: "सरासरी तयारी",
    dashSavedStandards: "जतन केलेली भारतीय मानके",
    dashMonitoredProds: "निरीक्षणाखालील उत्पादने",
    dashRecentSearches: "अलीकडील शोध इतिहास",
    dashReadinessCard: "एकूण अनुपालन तयारी",
    dashAlertsCard: "अलर्ट्स",
    dashShortcuts: "थेट विभाग लिंक",

    // Standards Explorer Page
    stdTitle: "मानक",
    stdItalic: "एक्सप्लोरर",
    stdSubtitle: "भारतीय मानके (IS), दुरुस्त्या, योजना आणि प्रयोगशाळांची माहिती शोधा व पडताळा.",
    stdPlaceholder: "IS क्रमांक (उदा. IS 302, IS 16046) किंवा कीवर्ड टाका...",
    stdMandatoryOnly: "फक्त अनिवार्य QCO",
    stdShowingCount: "जुळणारी मानके",
    stdKnowStandard: "आपले मानक जाणून घ्या",
    stdScopeApplication: "व्याप्ती आणि अनुप्रयोग",
    stdAmendmentsStatus: "दुरुस्ती स्थिती",
    stdStiStatus: "चाचणी योजना (STI)",

    // Compliance Checker Page
    compTitle: "अनुपालन",
    compItalic: "तपासक",
    compSubtitle: "चाचणी अहवालांचे भारतीय मानकांच्या अनिवार्य कलमांशी ताडून मूल्यांकन करा.",
    compNotice: "एआय मूल्यमापन सूचना: दिलेल्या माहितीनुसार निकष समर्थित दिसतात. हे कायदेशीर प्रमाणपत्र नाही. अंतिम प्रमाणीकरण बीआयएस अधिकारीच देतात.",
    compAuditedStd: "तपासलेले मानक",
    compFilterClauses: "कलम फिल्टर:",
    compParamCol: "कलम / पॅरामीटर",
    compSpecCol: "मानक विनिर्देश",
    compStatusCol: "मूल्यांकन स्थिती",
    compNotesCol: "पुरावे व नोंदी",

    // Application Readiness Page
    readTitle: "अर्ज",
    readItalic: "तयारी",
    readSubtitle: "बीआयएस परवाना दाखल करण्यापूर्वी कारखाना, प्रयोगशाळा आणि कागदपत्रांचे स्व-मूल्यांकन करा.",
    readNotice: "तयारी स्कोअर सूचना: ही टक्केवारी अंतर्गत स्व-मूल्यांकन आहे. हा बीआयएस मंजुरी स्कोअर नाही.",
    readConsolidated: "एकत्रित तयारी निर्देशक",
    readAdvancedStage: "प्रगत टप्पा",
    readSatisfiedCount: "निकष पूर्ण झाले",
    readPriorityNext: "प्राधान्य कृती",

    // BIS Lab Finder Page
    labTitle: "बीआयएस मान्यताप्राप्त",
    labItalic: "प्रयोगशाळा",
    labSubtitle: "आपल्या उत्पादनाची मानकांनुसार चाचणी घेण्यासाठी अधिकृत केंद्रीय, प्रादेशिक व NABL प्रयोगशाळा शोधा.",
    labPlaceholder: "मानक (उदा. IS 302), शहर किंवा प्रयोगशाळेचे नाव टाका...",
    labListMode: "यादी",
    labMapMode: "नकाशा",
    labShowingCount: "मान्यताप्राप्त प्रयोगशाळा",
    labScopeTitle: "चाचणी कार्यक्षेत्र:",
    labContactBtn: "संपर्क साधा",
    labMapTitle: "भौगोलिक प्रयोगशाळा नकाशा",
    labSendQuery: "चौकशी पाठवा",

    // Compare Standards Page
    compareTitle: "मानक",
    compareItalic: "तुलना",
    compareSubtitle: "दोन भारतीय मानकांमधील तांत्रिक तुलना. व्याप्ती, चाचणी पद्धती व नियमांमधील फरक समजून घ्या.",
    compareSelectPair: "तुलना जोडी निवडा:",
    compareDimCol: "तुलना घटक",
    compareScope: "व्याप्ती व उद्देश",
    compareCoverage: "उत्पादन व्याप्ती",
    compareTechReq: "तांत्रिक आवश्यकता",
    compareTests: "चाचणी पद्धती",
    compareMarking: "चिन्हांकन नियम",
    compareScheme: "प्रमाणीकरण योजना",

    // Updates & Alerts Page
    upTitle: "अपडेट्स व",
    upItalic: "अलर्ट्स",
    upSubtitle: "QCO आदेश, दुरुस्त्या आणि चाचणी नेटवर्क बदलांवर बारीक लक्ष ठेवा.",
    upNotice: "ट्रॅकिंग सूचना: मानक सारथी भारताचे राजपत्र आणि बीआयएस पोर्टलवरील प्रकाशित माहिती दर्शवते.",
    upUnreadOnly: "फक्त न वाचलेले",
    upMarkAllRead: "सर्व वाचलेले करा",
    upTimeline: "अंमलबजावणी मुदत:",
    upViewSource: "राजपत्र स्रोत पहा",

    // Common Badges, Descriptions & Extra Labels
    asstBadge: "भारतीय मानक ब्युरो • संवादात्मक मार्गदर्शन",
    stdCatalog: "बीआईएस मानक कॅटलॉग",
    accreditedLabs: "मान्यताप्राप्त चाचणी प्रयोगशाळा",
    findStandardDesc: "सोप्या भाषेत आपल्या उत्पादनाचे वर्णन करा",
    certDesc: "ISI, CRS आणि FMCS योजनांची टप्प्याटप्प्याने माहिती",
    labDesc: "राज्य आणि प्रादेशिक चाचणी प्रयोगशाळा शोधा",
    advisoryNotice: "सल्लागार सूचना",
    findBadge: "शोध मॉड्यूल • आपले मानक जाणून घ्या",
    docBadge: "विश्लेषण मॉड्यूल • स्रोत-आधारित दस्तऐवज एआय",
    certBadge: "मार्गदर्शन मॉड्यूल • अनुरूपता मूल्यांकन चौकट",
    dashBadge: "पोर्टफोलिओ व्यवस्थापक • एंटरप्राइझ अनुपालन",
    stdBadge: "राष्ट्रीय सूची • आपले मानक जाणून घ्या",
    compBadge: "पडताळणी मॉड्यूल • निदान ऑडिट",
    readBadge: "स्वयं-मूल्यांकन मॉड्यूल • अर्ज तत्परता",
    labBadge: "पायाभूत सुविधा नेटवर्क • NABL आणि बीआयएस प्रयोगशाळा",
    compareBadge: "विश्लेषणात्मक मॉड्यूल • तांत्रिक सुसंवाद",
    upBadge: "नियामक फीड • अधिकृत राजपत्र देखरेख",
    heroTitle: "गुणवत्तेचे सक्षमीकरण,",
    heroItalic: "विश्वासाची प्रेरणा",
    heroSubtitle: "सर्व औद्योगिक क्षेत्रांमध्ये भारतीय मानके, अनुरूपता मूल्यांकन आणि प्रयोगशाळा परिसंस्थेसाठी आपले एकमेव बुद्धिमान प्रवेशद्वार.",
    heroExplore: "सेवा एक्सप्लोर करा",
    heroAskAssistant: "एआई सहाय्यक मार्गदर्शन",
    trusted: "विश्वसनीय",
    transparent: "पारदर्शक",
    together: "एकत्रित",

    // Landing Page & Home Dashboard
    publicPortalBanner: "सार्वजनिक पोर्टल • भारतीय मानक ब्युरो",
    instantDemoLogin: "त्वरित डेमो लॉगिन (डॅशबोर्ड दृश्य)",
    returnToPublic: "← सार्वजनिक मुख्यपृष्ठावर परत जा",
    heroCard1Text: "आपल्या सुरक्षेसाठी बाजारातील उत्पादने बीआयएस मानकांचे पालन करतात.",
    heroCard2Text: "संपूर्ण भारतात २५ लाखांहून अधिक व्यवसाय आणि ग्राहकांचा विश्वास.",
    heroCard3Text: "आमच्या सेवांसाठी सरासरी ग्राहक समाधान रेटिंग.",
    heroExploreBtn: "आमच्या सेवा एक्सप्लोर करा",
    featMissionTag: "राष्ट्रीय गुणवत्ता पायाभूत सुविधा",
    featMissionTitle: "पारदर्शकता, अनुपालन आणि सुरक्षेसाठी सज्ज.",
    featMissionSub: "मानक सारथी उत्पादक, आयातदार, प्रयोगशाळा अधिकारी आणि भारतीय ग्राहकांसाठी मानक पडताळणी सुलभ करते.",
    featPillar1Title: "अनिवार्य सुरक्षा मानके",
    featPillar1Desc: "स्थानिक आणि आयात केलेल्या वस्तूंसाठी भारतीय मानक ब्युरोने प्रकाशित केलेल्या मानकांचा (IS) शोध.",
    featPillar2Title: "गुणवत्ता नियंत्रण आदेश (QCO)",
    featPillar2Desc: "७००+ उत्पादन श्रेणींमध्ये अनिवार्य प्रमाणीकरणासाठी राजपत्र अधिसूचना आणि मुदत ट्रॅक करा.",
    featPillar3Title: "मान्यताप्राप्त चाचणी नेटवर्क",
    featPillar3Desc: "सर्व भारतीय राज्यांमध्ये NABL-मान्यताप्राप्त चाचणी व कॅलिब्रेशन प्रयोगशाळा शोधा.",
    featCatalogTag: "वारंवार पाहिलेली",
    featCatalogTitle: "लोकप्रिय भारतीय मानके सूची",
    featExploreAll: "सर्व २०,०००+ मानके पहा",
    featStat1: "बाजार उत्पादन सुरक्षा अनुपालन",
    featStat2: "व्यवसाय आणि ग्राहक लाभान्वित",
    featStat3: "बीआयएस मान्यताप्राप्त चाचणी प्रयोगशाळा",
    featStat4: "गुणवत्ता नियंत्रण आदेश (QCOs)",
    featCtaTitle: "आपल्या उत्पादनाचे अनुपालन तपासण्यास सज्ज आहात का?",
    featCtaSub: "डॅशबोर्डमध्ये प्रवेश करण्यासाठी, भारतीय मानके तपासण्यासाठी आणि प्रमाणीकरण योजना ट्रॅक करण्यासाठी साइन इन करा.",
    featCtaSignIn: "पोर्टलवर साइन इन करा",
    featCtaExplore: "एआय मार्गदर्शन एक्सप्लोर करा",
    aiSearchTag: "भारतीय मानके • सत्यापित स्रोत • खरी उत्तरे",
    aiSearchTitle: "भारतीय मानके समजून घ्या,",
    aiSearchItalic: "पूर्ण आत्मविश्वासाने.",
    aiSearchSub: "भारतीय मानके, QCO आदेश, प्रमाणीकरण योजना आणि प्रयोगशाळांविषयी अचूक आणि अधिकृत माहिती एकाच ठिकाणी.",
    aiSearchPlaceholder: "उत्पादन, मानक किंवा नियमाबद्दल प्रश्न विचारा...",
    aiSearchPopularTopics: "लोकप्रिय मार्गदर्शन विषय:",
    catSectionTitle: "वर्गवारीनुसार एक्सप्लोर करा",
    catSectionSub: "अधिकृत मानके, आदेश, चाचणी नेटवर्क आणि प्रमाणीकरण मार्ग तपासा.",
    catViewAll: "सर्व पहा",
    catStdDesc: "नवीनतम भारतीय मानके (IS) शोधा आणि पहा.",
    catQcoDesc: "आपल्या उत्पादनासाठी लागू QCO आदेश शोधा.",
    catCertDesc: "ISI, CRS, FMCS आणि इतर योजनांची माहिती मिळवा.",
    catLabDesc: "मान्यताप्राप्त चाचणी आणि कॅलिब्रेशन प्रयोगशाळा शोधा.",
    catDocDesc: "मार्गदर्शक तत्त्वे, फॉर्म, सूचना आणि परिपत्रके.",
    footerTagline: "मानके • अनुपालन • विश्वास",
    footerMinistry: "ग्राहक व्यवहार विभाग (DoCA) • ग्राहक व्यवहार, अन्न आणि सार्वजनिक वितरण मंत्रालय",
    footerCopyright: "© २०२६ मानक सारथी • राष्ट्रीय गुणवत्ता पायाभूत सुविधांसाठी निर्मित.",
    footerLinkStandards: "मानक सूची",
    footerLinkAlerts: "राजपत्र अलर्ट्स",
    footerLinkLabs: "चाचणी प्रयोगशाळा",
    footerLinkAssistant: "एआय मार्गदर्शन",
  },
  te: {
    // Navigation & Global
    portalTitle: "మానక్ సారథి",
    nationalQuality: "జాతీయ నాణ్యత మౌలిక సదుపాయాలు",
    dashboardMode: "డాష్‌బోర్డ్ మోడ్",
    home: "హోమ్",
    assistant: "ఏఐ అసిస్టెంట్",
    findStandard: "ప్రమాణం వెతకండి",
    standards: "ప్రమాణాలు",
    qcos: "QCO ఆదేశాలు",
    certification: "ధృవీకరణ",
    labs: "ల్యాబ్‌లు",
    documents: "డాక్యుమెంట్ ఎనలైజర్",
    compliance: "కంప్లైయన్స్ చెకర్",
    readiness: "దరఖాస్తు సంసిద్ధత",
    compare: "ప్రమాణాల పోలిక",
    updates: "అప్‌డేట్లు & హెచ్చరికలు",
    dashboard: "డాష్‌బోర్డ్",
    more: "మరిన్ని",
    searchPlaceholder: "భారతీయ ప్రమాణాలు లేదా QCO కోసం శోధించండి...",
    signIn: "సైన్ ఇన్",
    signOut: "లాగ్ అవుట్",
    sourceGrounded: "మూలాధారిత AI",
    realTimeVerification: "ధృవీకరించబడిన మూలాలు",
    officialSource: "అధికారిక BIS మూలం",
    clause: "నిబంధన (Clause)",
    verifiedOn: "ధృవీకరించిన తేదీ",
    confidence: "విశ్వసనీయత",
    confidenceHigh: "అధిక విశ్వసనీయత",
    confidenceMed: "మధ్యస్థ విశ్వసనీయత",
    confidenceLow: "పరిశీలన అవసరం",
    exploreNow: "ఇప్పుడే అన్వేషించండి",
    viewDetails: "వివరాలు చూడండి",
    disclaimerLegal: "AI-సహాయక మార్గదర్శకత్వం. అధికారిక ధృవీకరణ మరియు పరీక్ష నిర్ణయాలు భారతీయ ప్రమాణాల బ్యూరో (BIS) పరిధిలోనే ఉంటాయి.",
    evidenceFound: "ఆధారం లభించింది",
    missingEvidence: "ఆధారం లేదు",
    manualVerification: "మాన్యువల్ పరిశీలన అవసరం",
    backToHome: "హోమ్‌కు తిరిగి వెళ్లండి",
    reset: "రీసెట్",
    search: "శోధించండి",
    proceed: "ముందుకు సాగండి",
    copy: "కాపీ చేయండి",
    copied: "కాపీ అయింది",
    officialRecord: "అధికారిక BIS రికార్డు",
    allCategories: "అన్ని వర్గాలు",
    allStates: "అన్ని రాష్ట్రాలు",
    allDomains: "అన్ని రంగాలు",

    // Admin Panel Translations (Telugu)
    adminDashboard: "అడ్మిన్ డాష్‌బోర్డ్",
    adminBrand: "బిఐఎస్ గైడెన్స్",
    welcomeBack: "తిరిగి స్వాగతం,",
    welcomeHeading: "ఈ రోజు బిఐఎస్ గైడెన్స్‌లో విశేషాలు.",
    welcomeSubtext: "ఫ్లాట్‌ఫారమ్‌లో ప్రధాన గణాంకాలు మరియు ఇటీవల కార్యకలాపాలు.",
    quickActions: "త్వరిత చర్యలు",
    totalStandards: "మొత్తం ప్రమాణాలు",
    activeQcos: "యాక్టివ్ QCOలు",
    certificationSchemes: "సర్టిఫికేషన్ పథకాలు",
    recognizedLabs: "గుర్తింపు పొందిన ల్యాబ్‌లు",
    recentActivity: "ఇటీవలి కార్యకలాపాలు",
    topQueries: "ప్రధాన ప్రశ్నలు",
    viewAll: "అన్నీ చూడండి →",
    addNewStandard: "కొత్త ప్రమాణాన్ని జోడించు",
    createQco: "QCO సృష్టించు",
    addCertScheme: "సర్టిఫికేషన్ పథకాన్ని జోడించు",
    registerLab: "ల్యాబ్‌ను నమోదు చేయండి",
    searchAdminPlaceholder: "ప్రమాణాలు, QCOలు, సర్టిఫికేషన్‌లను శోధించండి...",
    systemOnline: "సిస్టమ్ ఆన్‌లైన్",
    adminSection: "అడ్మిన్",
    userManagement: "వినియోగదారు నిర్వహణ",
    systemLogs: "సిస్టమ్ లాగ్‌లు",
    settings: "సెట్టింగ్‌లు",
    thisMonth: "ఈ నెలలో",
    adminProfile: "అడ్మిన్",
    cancel: "రద్దు చేయి",
    saveRecord: "రికార్డు భద్రపరచు",
    actions: "చర్యలు",
    noRecordsFound: "ఎలాంటి రికార్డులు కనుగొనబడలేదు",
    noRecordsMsg: "మీ శోధనకు తగిన ఫలితాలు లేవు.",
    showing: "చూపిస్తోంది",
    to: "నుండి",
    of: "లో",
    entries: "ఎంట్రీలు",
    filterRecords: "ఫిల్టర్ చేయండి...",
    actNewStandard: "కొత్త భారతీయ ప్రమాణం జోడించబడింది",
    actQcoUpdated: "QCO అప్‌డేట్ చేయబడింది",
    actNewScheme: "కొత్త సర్టిఫికేషన్ పథకం",
    actNewLab: "కొత్త ల్యాబ్ నమోదు చేయబడింది",
    query1: "మొబైల్ ఛార్జర్లకు బిఐఎస్ సర్టిఫికేషన్",
    query2: "ఎలక్ట్రికల్ వస్తువులకు QCO వర్తింపు",
    query3: "నా దగ్గరలో ఉన్న బిఐఎస్ ల్యాబ్‌లను కనుగొనండి",
    query4: "ఆహార ప్యాకేజింగ్ కోసం భారతీయ ప్రమాణాలు (IS)",
    query5: "బొమ్మలలో ప్రమాదకర పదార్థాలు (QCO)",

    // Inner Admin Pages (Telugu)
    stdPageTitle: "భారతీయ ప్రమాణాల జాబితా",
    stdPageDesc: "అన్ని రంగాలలో ధృవీకరించబడిన భారతీయ ప్రమాణాలు (IS), నిబంధనలు మరియు సాంకేతిక వివరణలను నిర్వహించండి.",
    addNewStandardBtn: "కొత్త ప్రమాణాన్ని జోడించు",
    searchByIsOrTitle: "IS సంఖ్య లేదా శీర్షిక శోధించండి...",
    allSectors: "అన్ని రంగాలు",
    allStatuses: "అన్ని హోదాలు",
    colIsNumber: "IS సంఖ్య",
    colStdTitleScope: "ప్రమాణ శీర్షిక & పరిధి",
    colSector: "రంగం",
    colStatus: "హోదా",
    colLastRevised: "చివరి సవరణ",
    techClauses: "సాంకేతిక నిబంధనలు",

    qcoPageTitle: "నాణ్యతా నియంత్రణ ఉత్తర్వులు (QCOలు)",
    qcoPageDesc: "అధికారిక గెజిట్ నోటిఫికేషన్లు, తప్పనిసరి సర్టిఫికేషన్ ఆదేశాలు మరియు మంత్రిత్వ శాఖ అమలు తేదీలను పర్యవేక్షించండి.",
    createQcoBtn: "QCO ఆదేశం సృష్టించు",
    searchQcoPlaceholder: "QCO కోడ్, శీర్షిక లేదా మంత్రిత్వ శాఖను శోధించండి...",
    allMandateStatuses: "అన్ని ఆదేశ హోదాలు",
    colQcoRef: "QCO రెఫరెన్స్",
    colQcoSubject: "QCO అంశం & పరిధి",
    colNotifiedDate: "నోటిఫై చేసిన తేదీ",
    colEnforcementDate: "అమలు తేదీ",
    colMandateStatus: "ఆదేశ హోదా",

    certPageTitle: "చట్టబద్ధమైన సర్టిఫికేషన్ పథకాలు",
    certPageDesc: "BIS నాణ్యత మూల్యాంకన విధానాలు, ఫ్యాక్టరీ తనిఖీ నిబంధనలు మరియు లైసెన్స్ మార్గదర్శకాలను కాన్ఫిగర్ చేయండి.",
    addSchemeBtn: "సర్టిఫికేషన్ పథకాన్ని జోడించు",
    searchCertPlaceholder: "సర్టిఫికేషన్ పథకాలను శోధించండి...",
    colSchemeCode: "పథకం కోడ్",
    colConformityScheme: "నాణ్యతా మూల్యాంకన పథకం",
    colMappedStandards: "మ్యాప్ చేసిన ప్రమాణాలు",
    colSurveillanceRule: "ఆడిట్ / తనిఖీ నిబంధన",
    colOpStatus: "కార్యాచరణ హోదా",

    labPageTitle: "BIS-గుర్తింపు పొందిన ల్యాబ్‌లు",
    labPageDesc: "గుర్తింపు పొందిన పరీక్షా కేంద్రాలు, NABL అనుసంధానం మరియు ల్యాబ్ పరీక్షల పరిధిని నిర్వహించండి.",
    registerLabBtn: "ల్యాబ్‌ను నమోదు చేయండి",
    searchLabPlaceholder: "ల్యాబ్ పేరు, ప్రదేశం లేదా ప్రమాణాలను శోధించండి...",
    colLabCode: "ల్యాబ్ కోడ్",
    colLabNameLoc: "ల్యాబ్ పేరు & ప్రదేశం",
    colTestingScope: "గుర్తింపు పొందిన పరీక్షా పరిధి",
    colValidity: "గుర్తింపు గడువు",

    docPageTitle: "డాక్యుమెంట్ డిపాజిటరీ & గెజిట్ సూచిక",
    docPageDesc: "AI ఇండెక్స్ సంగ్రహణ కోసం అధికారిక BIS గెజిట్ నోటిఫికేషన్లు మరియు ప్రమాణాల పత్రాలను అప్‌లోడ్ చేయండి.",
    uploadGazetteBtn: "గెజిట్ / PDF అప్‌లోడ్ చేయండి",
    searchDocPlaceholder: "డాక్యుమెంట్ పేరు లేదా వర్గాన్ని శోధించండి...",
    colFileName: "డాక్యుమెంట్ ఫైల్ పేరు",
    colCategory: "వర్గం",
    colFileSize: "ఫైల్ పరిమాణం",
    colIndexedStandards: "సూచిక చేసిన ప్రమాణాలు",
    colUploadedDate: "అప్‌లోడ్ చేసిన తేదీ",

    usrPageTitle: "వినియోగదారు నిర్వహణ & యాక్సెస్ నిరోధాలు",
    usrPageDesc: "సిస్టమ్ అడ్మినిస్ట్రేటర్ హక్కులు, మంత్రిత్వ శాఖ నోడల్ ఖాతాలు మరియు ల్యాబ్ ఆడిటర్ అనుమతులను నిర్వహించండి.",
    provisionUserBtn: "కొత్త వినియోగదారుని జోడించు",
    searchUserPlaceholder: "వినియోగదారు పేరు, ఈమెయిల్ లేదా విభాగాన్ని శోధించండి...",
    allUserRoles: "అన్ని వినియోగదారు పాత్రలు",
    colUserProfile: "వినియోగదారు ప్రొఫైల్ & ఈమెయిల్",
    colAccessRole: "యాక్సెస్ పాత్ర",
    colOrgDept: "సంస్థ / విభాగం",
    colLastActive: "చివరి సక్రియం",
    colAccountStatus: "ఖాతా హోదా",

    logPageTitle: "సిస్టమ్ ఆడిట్ లాగ్‌లు & భద్రతా రికార్డు",
    logPageDesc: "పరిపాలనా చర్యలు, QCO గెజిట్ సవరణలు, భద్రతా ఈవెంట్లు మరియు AI సింక్ యొక్క మార్చలేని రికార్డు.",
    exportLogBtn: "ఆడిట్ లాగ్ ఎగుమతి చేయండి (CSV)",
    searchLogPlaceholder: "ఆడిట్ ఈవెంట్లు, వినియోగదారులు లేదా వనరులను శోధించండి...",
    allSeverities: "అన్ని తీవ్రత స్థాయిలు",
    colTimestamp: "సమయం",
    colActorSystem: "వినియోగదారు / సిస్టమ్",
    colEventAction: "ఈవెంట్ చర్య",
    colTargetResource: "లక్ష్య వనరు",
    colSeverity: "తీవ్రత",

    setPageTitle: "సిస్టమ్ & ఫ్లాట్‌ఫారమ్ సెట్టింగ్‌లు",
    setPageDesc: "అడ్మిన్ ప్రొఫైల్ వివరాలు, AI ఇండెక్స్ పారామితులు మరియు భద్రతా విధానాలను కాన్ఫిగర్ చేయండి.",
    tabAccount: "ఖాతా ప్రొఫైల్",
    tabPlatform: "ఫ్లాట్‌ఫారమ్ & AI సమాచారం",
    tabSecurity: "భద్రత & యాక్సెస్",
    tabNotifications: "నోటిఫికేషన్లు & హెచ్చరికలు",
    saveSettingsBtn: "సెట్టింగ్‌లను భద్రపరచు",

    statusActive: "యాక్టివ్",
    statusUnderReview: "పరిశీలనలో ఉంది",
    statusDraft: "డ్రాఫ్ట్",
    statusEnforced: "అమల్లో ఉంది",
    statusRecognized: "గుర్తింపు పొందింది",
    statusSuspended: "సస్పెండ్ చేయబడింది",

    edit: "ఎడిట్ చేయి",
    delete: "తొలగించు",
    sectorMechanical: "మెకానికల్",
    sectorElectronics: "ఎలక్ట్రానిక్స్",
    sectorElectrical: "ఎలక్ట్రికల్",
    sectorConsumerGoods: "వినియోగ వస్తువులు",
    sectorLighting: "లైటింగ్",
    sectorTelecom: "టెలికామ్",

    stdTitle1: "పారిశ్రామిక పంపులు మరియు ద్రవ నిర్వహణ కొరకు భద్రతా అవసరాలు",
    stdTitle2: "సమాచార సాంకేతిక పరికరాలు — భద్రతా అవసరాలు",
    stdTitle3: "బొమ్మల భద్రత — మెకానికల్ మరియు భౌతిక లక్షణాలు",
    stdTitle4: "1100V వరకు పని చేసే వోల్టేజీల కోసం పాలివినైల్ క్లోరైడ్ ఇన్సులేటెడ్ కేబుల్స్",
    stdTitle5: "ల్యాంప్ కంట్రోల్‌గేర్ భద్రత — LED కోసం AC లేదా DC ఎలక్ట్రానిక్ కంట్రోల్‌గేర్",
    stdTitle6: "మొబైల్ ఫోన్ హ్యాండ్‌సెట్‌లు — భారతీయ భాషా మద్దతు అవసరాలు",

    qcoTitle1: "ఎలక్ట్రికల్ పరికరాల (నాణ్యత నియంత్రణ) సవరణ ఉత్తర్వు, 2025",
    qcoTitle2: "బొమ్మల (నాణ్యత నియంత్రణ) ఉత్తర్వు, 2024 ఆదేశం",
    qcoTitle3: "సౌర PV వ్యవస్థలు మరియు విడిభాగాల నాణ్యత ఉత్తర్వు",
    qcoTitle4: "రసాయనాలు & పెట్రోకెమికల్స్ (నాణ్యత నియంత్రణ) ఆదేశం",
    qcoMin1: "DPIIT / భారీ పరిశ్రమల మంత్రిత్వ శాఖ",
    qcoMin2: "వాణిజ్య & పరిశ్రమల మంత్రిత్వ శాఖ",
    qcoMin3: "నూతన & పునరుద్ధరణీయ ఇంధన మంత్రిత్వ శాఖ",
    qcoMin4: "రసాయనాలు & పెట్రోకెమికల్స్ విభాగం",

    schName1: "ఉత్పత్తి సర్టిఫికేషన్ పథకం (ISI మార్క్)",
    schName2: "తప్పనిసరి నమోదు పథకం (CRS)",
    schName3: "విదేశీ తయారీదారుల సర్టిఫికేషన్ పథకం (FMCS)",
    schName4: "విలువైన లోహాల హాల్‌మార్కింగ్ (HUID)",
    schAudience1: "దేశీయ తయారీదారులు & ఫ్యాక్టరీలు",
    schAudience2: "ఎలక్ట్రానిక్స్ & IT వస్తువుల తయారీదారులు",
    schAudience3: "భారతదేశానికి విదేశీ ఎగుమతిదారులు",
    schAudience4: "స్వర్ణకారులు & హాల్‌మార్కింగ్ కేంద్రాలు",
    schRule1: "వార్షిక ఆడిట్ & మార్కెట్ నమూనా పరిశీలన",
    schRule2: "ల్యాబ్ పరీక్షతో స్వీయ-ప్రకటన",
    schRule3: "లైసెన్స్ ముందస్తు విదేశీ ఫ్యాక్టరీ తనిఖీ",
    schRule4: "రియల్ టైమ్ పోర్టల్ ఆడిట్ & శాంప్లింగ్",

    labName1: "థర్మో టెస్ట్ ల్యాబ్స్ ప్రైవేట్ లిమిటెడ్",
    labName2: "నేషనల్ టెస్టింగ్ హౌస్ (NTH)",
    labName3: "ఎపెక్స్ ప్రిసిషన్ క్యాలిబ్రేషన్ & టెస్ట్ ఫెసిలిటీ",
    labName4: "సన్ ఎనర్జీ PV టెస్ట్ సెంటర్",
    labScope1: "పంపులు, మోటార్లు & ఇండస్ట్రియల్ కేబుల్స్ (IS 17431, IS 694)",
    labScope2: "ఎలక్ట్రానిక్స్, IT పరికరాలు & బ్యాటరీలు (IS 13252)",
    labScope3: "బొమ్మల భద్రత, రసాయనిక విశ్లేషణ (IS 9873)",
    labScope4: "సౌర మాడ్యూళ్లు & ఇన్వర్టర్లు (IS 14286)",

    docCatQco: "QCO నోటిఫికేషన్",
    docCatStd: "ప్రమాణాల గెజిట్",
    docCatTest: "పరీక్షా ప్రోటోకాల్",
    docCited: "పేర్కొనబడింది",

    roleAdmin: "సిస్టమ్ అడ్మినిస్ట్రేటర్",
    roleNodal: "మంత్రిత్వ శాఖ నోడల్ అధికారి",
    roleLabAdmin: "ల్యాబ్ అడ్మినిస్ట్రేటర్",
    roleAuditor: "ప్రమాణాల ఆడిటర్",

    logAct1: "గెజిట్ ప్రమాణం ప్రచురించబడింది",
    logAct2: "ఆటోమేటెడ్ వెక్టర్ ఇండెక్స్ సింక్",
    logAct3: "QCO అమలు తేదీ సవరించబడింది",
    logAct4: "విఫలమైన ప్రామాణీకరణ ప్రయత్నం",

    displayName: "ప్రదర్శన పేరు",
    officialEmail: "అధికారిక ఈమెయిల్",
    adminProfileTitle: "అడ్మినిస్ట్రేటర్ ప్రొఫైల్",
    settingsUpdatedMsg: "సెట్టింగ్‌లు విజయవంతంగా అప్‌డేట్ చేయబడ్డాయి!",
    deptDivision: "విభాగం / డివిజన్",
    timezoneLabel: "సమయ మండలి",
    userRoleLabel: "పాత్ర హక్కులు",
    aiGroundingModel: "AI గ్రౌండింగ్ మోడల్",
    confidenceThreshold: "విశ్వసనీయత పరిమితి",
    autoIndexPdf: "గెజిట్ PDF ఆటో ఇండెక్సింగ్",
    maxCitations: "ప్రశ్నకు గరిష్ట ఉల్లేఖనాలు",
    enable2FA: "ద్వి-అంచెల ప్రామాణీకరణ (2FA)",
    sessionTimeout: "సెషన్ ముగింపు కాలం",
    ipRestriction: "IP యాక్సెస్ నిరోధం",
    qcoAlerts: "QCO గెజిట్ ఈమెయిల్ హెచ్చరికలు",
    securityAlerts: "భద్రత & లాగిన్ హెచ్చరికలు",
    labExpiryAlerts: "ల్యాబ్ గడువు హెచ్చరికలు",

    // AI Assistant Page
    asstTitle: "మూలాధారిత",
    asstItalic: "AI అసిస్టెంట్",
    asstSubtitle: "ధృవీకరించబడిన భారతీయ ప్రమాణాల సమాచారంతో నేరుగా సంభాషించండి. మూలాధారాలు, నిబంధనలు మరియు తక్షణ సమ్మతి చర్యలను పొందండి.",
    asstSession: "రియల్ టైమ్ సెషన్",
    asstSessionSub: "ధృవీకరించబడిన BIS గెజిట్లు & IS కోడ్‌లు",
    asstWelcome: "నమస్కారం! నేను మీ మానక్ సారథి AI అసిస్టెంట్‌ని. భారతీయ ప్రమాణాలు (IS), నాణ్యతా నియంత్రణ ఉత్తర్వులు (QCO) మరియు ధృవీకరణ పథకాలపై మార్గదర్శకత్వం అందిస్తాను.",
    asstWorkflowSteps: "సిఫార్సు చేయబడిన తదుపరి చర్యలు:",
    asstSourcesTitle: "ధృవీకరించబడిన డేటా మూలాలు",
    asstSourcesDesc: "మానక్ సారథి ఇచ్చే ప్రతి సమాధానం BIS మరియు కేంద్ర మంత్రిత్వ శాఖల అధికారిక డేటాతో సరిచూడబడుతుంది.",
    asstJumpTitle: "ముఖ్య విభాగాలకు వెళ్లండి",
    asstAdvisoryNotice: "ఈ AI అసిస్టెంట్ సమాచార మార్గదర్శకత్వం మాత్రమే అందిస్తుంది. తుది ధృవీకరణ మరియు పరీక్ష నిర్ణయాలు BIS అధికారులకే చెందుతాయి.",
    asstAskPlaceholder: "భారతీయ ప్రమాణాలు, ఉత్పత్తులు లేదా నియమాల గురించి అడగండి...",

    // Find My Standard Page
    findTitle: "మీ ప్రమాణాన్ని",
    findItalic: "కనుగొనండి",
    findSubtitle: "మీ ఉత్పత్తి వివరణ, మెటీరియల్ మరియు ఉద్దేశ్యాన్ని బట్టి వర్తించే భారతీయ ప్రమాణాలు మరియు QCO నిబంధనలను కనుగొనండి.",
    findTryPreset: "నమూనా తయారీ విధానాన్ని ఎంచుకోండి:",
    findProfileTitle: "ఉత్పత్తి ప్రొఫైల్",
    findProdName: "ఉత్పత్తి పేరు *",
    findProdDesc: "సమగ్ర ఉత్పత్తి వివరణ",
    findMaterial: "ప్రధాన మెటీరియల్",
    findIndustry: "పరిశ్రమ రంగం",
    findIntendedUse: "ఉద్దేశించిన ఉపయోగం",
    findBtn: "వర్తించే ప్రమాణాలను కనుగొనండి",
    findSearching: "భారతీయ ప్రమాణాల జాబితాలో శోధిస్తోంది...",
    findResultsTitle: "సంబంధిత భారతీయ ప్రమాణాలు",
    findResultsFor: "మూల్యాంకనం చేసిన ఉత్పత్తి:",
    findScopeAssessment: "పరిధి మూల్యాంకనం:",
    findKeySpecs: "ముఖ్య పరీక్ష ప్రమాణాలు:",
    findNotice: "గమనిక: ప్రమాణాల గుర్తింపు ప్రాథమిక వివరణపై ఆధారపడి ఉంటుంది. అధికారిక నిర్ధారణను BIS కార్యాలయంలో సరిచూసుకోవాలి.",

    // Document Analyzer Page
    docTitle: "పత్ర",
    docItalic: "విశ్లేషకం",
    docSubtitle: "BIS నాణ్యతా నియంత్రణ ఉత్తర్వులు మరియు ల్యాబ్ పరీక్ష నివేదికలను అప్‌లోడ్ చేయండి. AI ప్రమాణాలు మరియు నిబంధనలను స్వయంచాలకంగా విశ్లేషిస్తుంది.",
    docSampleSelector: "విశ్లేషణ కోసం నమూనా పత్రాన్ని ఎంచుకోండి:",
    docUploadTitle: "BIS పత్రాన్ని అప్‌లోడ్ చేయండి",
    docUploadDesc: "QCO గెజిట్ లేదా NABL టెస్ట్ రిపోర్ట్ (PDF, DOCX గరిష్టంగా 25MB)",
    docSelectFile: "లోకల్ ఫైల్‌ను ఎంచుకోండి",
    docClassTitle: "పత్ర వర్గీకరణ",
    docTimelinesTitle: "ముఖ్యమైన గడువులు & తేదీలు",
    docExtractedTitle: "గుర్తించిన భారతీయ ప్రమాణాలు",
    docReqTitle: "గుర్తించిన ఆవశ్యకతలు",
    docMissingTitle: "లోపించిన సమాచారం",
    docInquireTitle: "ఈ పత్రం గురించి అడగండి",
    docInquirePlaceholder: "నిబంధనలు లేదా పరీక్షల గురించి అడగండి...",
    docInquireBtn: "అడగండి",

    // Certification Navigator Page
    certTitle: "ధృవీకరణ",
    certItalic: "నావిగేటర్",
    certSubtitle: "BIS ధృవీకరణ పథకాలు, అవసరమైన పత్రాలు మరియు దశలవారీ విధానాన్ని అర్థం చేసుకోండి.",
    certAdvisoryNotice: "మార్గదర్శక గమనిక: ఈ నావిగేటర్ విద్యాపరమైన మార్గదర్శకత్వం మాత్రమే ఇస్తుంది. అధికారిక దరఖాస్తులను BIS పోర్టల్‌లోనే సమర్పించాలి.",
    certViewFlow: "పథకం విధానాన్ని చూడండి",
    certTimelineTitle: "విధాన ప్రక్రియ & కాలక్రమం",
    certDossierTitle: "అవసరమైన పత్రాల దస్త్రం",
    certDossierDesc: "BIS పోర్టల్‌లో అధికారికంగా దరఖాస్తు చేయడానికి ముందు తయారీదారులు కింది పత్రాలను సిద్ధం చేసుకోవాలి:",
    certTestingTitle: "పరీక్ష & ల్యాబ్ నిబంధనలు",
    certAuditTitle: "ఫ్యాక్టరీ నాణ్యతా తనిఖీ",
    certStatutoryRef: "అధికారిక చట్టబద్ధమైన మూలం",

    // My Dashboard Page
    dashTitle: "తయారీదారుల",
    dashItalic: "డాష్‌బోర్డ్",
    dashSubtitle: "సేవ్ చేసిన ప్రమాణాలు, ఉత్పత్తులు మరియు ల్యాబ్ పరీక్షల పురోగతిని ఒకే చోట పర్యవేక్షించండి.",
    dashTrackNew: "కొత్త ఉత్పత్తిని ట్రాక్ చేయండి",
    dashVerifiedEntity: "ధృవీకరించబడిన సంస్థ",
    dashTrackedCount: "ట్రాక్ చేస్తున్న ప్రమాణాలు",
    dashPortfolioAvg: "సగటు సంసిద్ధత",
    dashSavedStandards: "సేవ్ చేసిన భారతీయ ప్రమాణాలు",
    dashMonitoredProds: "పర్యవేక్షణలో ఉన్న ఉత్పత్తులు",
    dashRecentSearches: "ఇటీవలి శోధన చరిత్ర",
    dashReadinessCard: "మొత్తం సమ్మతి సంసిద్ధత",
    dashAlertsCard: "హెచ్చరికలు",
    dashShortcuts: "ముఖ్య విభాగాలు",

    // Standards Explorer Page
    stdTitle: "ప్రమాణాల",
    stdItalic: "అన్వేషకం",
    stdSubtitle: "భారతీయ ప్రమాణాలు (IS), సవరణలు, పథకాలు మరియు ల్యాబ్‌ల వివరాలను శోధించి ధృవీకరించండి.",
    stdPlaceholder: "IS నంబర్ (ఉదా. IS 302, IS 16046) లేదా కీవర్డ్ నమోదు చేయండి...",
    stdMandatoryOnly: "తప్పనిసరి QCO మాత్రమే",
    stdShowingCount: "సరిపోలిన ప్రమాణాలు",
    stdKnowStandard: "మీ ప్రమాణాన్ని తెలుసుకోండి",
    stdScopeApplication: "పరిధి మరియు అప్లికేషన్",
    stdAmendmentsStatus: "సవరణల స్థితి",
    stdStiStatus: "పరీక్షా పథకం (STI)",

    // Compliance Checker Page
    compTitle: "సమ్మతి",
    compItalic: "తనిఖీ",
    compSubtitle: "పరీక్ష నివేదికలను భారతీయ ప్రమాణాల తప్పనిసరి నిబంధనలతో సరిపోల్చి అంచనా వేయండి.",
    compNotice: "AI అంచనా గమనిక: అందించిన సమాచారం ఆధారంగా కింది నిబంధనలు సరిపోయినట్లు కనిపిస్తున్నాయి. ఇది చట్టపరమైన ధృవీకరణ కాదు. తుది ధృవీకరణను BIS అధికారులు మాత్రమే ఇస్తారు.",
    compAuditedStd: "తనిఖీ చేసిన ప్రమాణం",
    compFilterClauses: "నిబంధనల ఫిల్టర్:",
    compParamCol: "నిబంధన / పరామితి",
    compSpecCol: "ప్రమాణ నిర్దేశాలు",
    compStatusCol: "మూల్యాంకన స్థితి",
    compNotesCol: "ఆధారాలు & గమనికలు",

    // Application Readiness Page
    readTitle: "దరఖాస్తు",
    readItalic: "సంసిద్ధత",
    readSubtitle: "BIS లైసెన్స్ కోసం దరఖాస్తు చేసే ముందు ఫ్యాక్టరీ, ల్యాబ్ మరియు పత్రాల సంసిద్ధతను స్వీయ-మూల్యాంకనం చేసుకోండి.",
    readNotice: "సంసిద్ధత స్కోర్ గమనిక: ఈ శాతం అంతర్గత స్వీయ-మూల్యాంకనం మాత్రమే. ఇది లైసెన్స్ మంజూరుకు హామీ ఇవ్వదు.",
    readConsolidated: "మొత్తం సంసిద్ధతా సూచిక",
    readAdvancedStage: "ఉన్నత దశ",
    readSatisfiedCount: "అంశాలు సంతృప్తికరంగా ఉన్నాయి",
    readPriorityNext: "ప్రాధాన్యతా చర్యలు",

    // BIS Lab Finder Page
    labTitle: "BIS గుర్తింపు పొందిన",
    labItalic: "ల్యాబ్‌లు",
    labSubtitle: "మీ ఉత్పత్తిని తప్పనిసరి ప్రమాణాల ప్రకారం పరీక్షించడానికి అధీకృత ల్యాబ్‌లను కనుగొనండి.",
    labPlaceholder: "ప్రమాణం (ఉదా. IS 302), నగరం లేదా ల్యాబ్ పేరుతో శోధించండి...",
    labListMode: "జాబితా",
    labMapMode: "మ్యాప్",
    labShowingCount: "గుర్తింపు పొందిన ల్యాబ్‌లు",
    labScopeTitle: "గుర్తింపు పొందిన పరీక్షా పరిధి:",
    labContactBtn: "ల్యాబ్‌ను సంప్రదించండి",
    labMapTitle: "ల్యాబ్‌ల భౌగోళిక పటం",
    labSendQuery: "పరీక్షా విచారణ పంపండి",

    // Compare Standards Page
    compareTitle: "ప్రమాణాల",
    compareItalic: "పోలిక",
    compareSubtitle: "రెండు భారతీయ ప్రమాణాల మధ్య సాంకేతిక పోలిక. పరిధి, పరీక్షా పద్ధతులు మరియు నిబంధనల తేడాలను విశ్లేషించండి.",
    compareSelectPair: "పోలిక జతను ఎంచుకోండి:",
    compareDimCol: "పోలిక అంశం",
    compareScope: "పరిధి మరియు ఉద్దేశ్యం",
    compareCoverage: "ఉత్పత్తి పరిధి",
    compareTechReq: "సాంకేతిక ఆవశ్యకతలు",
    compareTests: "కీలక పరీక్షా పద్ధతులు",
    compareMarking: "మార్కింగ్ నిబంధనలు",
    compareScheme: "ధృవీకరణ పథకం",

    // Updates & Alerts Page
    upTitle: "అప్‌డేట్లు &",
    upItalic: "హెచ్చరికలు",
    upSubtitle: "QCO ఆర్డర్లు, సవరణలు మరియు ల్యాబ్ నెట్‌వర్క్ మార్పులను నిరంతరం పర్యవేక్షించండి.",
    upNotice: "ట్రాకింగ్ గమనిక: మానక్ సారథి గెజిట్ ఆఫ్ ఇండియా మరియు BIS పోర్టల్ నుండి సమాచారాన్ని అందిస్తుంది.",
    upUnreadOnly: "చదవనివి మాత్రమే",
    upMarkAllRead: "అన్నీ చదివినట్లు గుర్తించండి",
    upTimeline: "అమలు గడువు:",
    upViewSource: "గెజిట్ మూలాన్ని చూడండి",

    // Common Badges, Descriptions & Extra Labels
    asstBadge: "భారతీయ ప్రమాణాల బ్యూరో • సంభాషణ మార్గదర్శకత్వం",
    stdCatalog: "BIS ప్రమాణాల కేటలాగ్",
    accreditedLabs: "గుర్తింపు పొందిన టెస్టింగ్ ల్యాబ్‌లు",
    findStandardDesc: "సహజ భాషలో మీ ఉత్పత్తిని వివరించండి",
    certDesc: "దశలవారీ ISI, CRS మరియు FMCS పథకాలు",
    labDesc: "రాష్ట్ర మరియు ప్రాంతీయ పరీక్షా కేంద్రాలను గుర్తించండి",
    advisoryNotice: "సలహా నోటీసు",
    findBadge: "డిస్కవరీ మాడ్యూల్ • మీ ప్రమాణాన్ని తెలుసుకోండి",
    docBadge: "విశ్లేషణ మాడ్యూల్ • మూల-ఆధారిత డాక్యుమెంట్ ఏఐ",
    certBadge: "మార్గదర్శక మాడ్యూల్ • అనురూప్యత మూల్యాంకన ఫ్రేమ్‌వర్క్",
    dashBadge: "పోర్ట్‌ఫోలియో మేనేజర్ • ఎంటర్‌ప్రైజ్ సమ్మతి",
    stdBadge: "జాతీయ జాబితా • మీ ప్రమాణాన్ని తెలుసుకోండి",
    compBadge: "ధృవీకరణ మాడ్యూల్ • రోగనిర్ధారణ ఆడిట్",
    readBadge: "స్వీయ-మూల్యాంకన మాడ్యూల్ • దరఖాస్తు సంసిద్ధత",
    labBadge: "మౌలిక సదుపాయాల నెట్‌వర్క్ • NABL & BIS ప్రయోగశాలలు",
    compareBadge: "విశ్లేషణాత్మక మాడ్యూల్ • సాంకేతిక సమన్వయం",
    upBadge: "నియంత్రణ ఫీడ్ • అధికారిక గెజిట్ పర్యవేక్షణ",
    heroTitle: "నాణ్యతను సాధికారపరచడం,",
    heroItalic: "విశ్వాసాన్ని ప్రేరేపించడం",
    heroSubtitle: "అన్ని పారిశ్రామిక రంగాలలో భారతీయ ప్రమాణాలు, అనురూప్యత మూల్యాంకనం మరియు ప్రయోగశాల వ్యవస్థలకు మీ ఏకైక మార్గదర్శి.",
    heroExplore: "సేవలను అన్వేషించండి",
    heroAskAssistant: "ఏఐ అసిస్టెంట్ మార్గదర్శకత్వం",
    trusted: "విశ్వసనీయమైనది",
    transparent: "పారదర్శకమైనది",
    together: "కలిసికట్టుగా",

    // Landing Page & Home Dashboard
    publicPortalBanner: "పబ్లిక్ పోర్టల్ • బ్యూరో ఆఫ్ ఇండియన్ స్టాండర్డ్స్",
    instantDemoLogin: "తక్షణ డెమో లాగిన్ (డాష్‌బోర్డ్ వీక్షణ)",
    returnToPublic: "← పబ్లిక్ హోమ్‌పేజీకి తిరిగి వెళ్లండి",
    heroCard1Text: "మీ భద్రత కోసం మార్కెట్‌లోని ఉత్పత్తులు BIS ప్రమాణాలకు అనుగుణంగా ఉంటాయి.",
    heroCard2Text: "భారతదేశం అంతటా 25 లక్షలకు పైగా వ్యాపారులు మరియు వినియోగదారుల నమ్మకం.",
    heroCard3Text: "మా సేవల కోసం సగటు కస్టమర్ రేటింగ్.",
    heroExploreBtn: "మా సేవలను అన్వేషించండి",
    featMissionTag: "జాతీయ నాణ్యత మౌలిక సదుపాయాలు",
    featMissionTitle: "పారదర్శకత, సమ్మతి మరియు భద్రత కోసం నిర్మించబడింది.",
    featMissionSub: "ఉత్పత్తిదారులు, దిగుమతిదారులు మరియు వినియోగదారుల కోసం ప్రమాణాల ధృవీకరణను మానక్ సారథి సులభతరం చేస్తుంది.",
    featPillar1Title: "తప్పనిసరి భద్రతా ప్రమాణాలు",
    featPillar1Desc: "దేశీయ మరియు దిగుమతి చేసుకున్న వస్తువుల కోసం BIS ప్రచురించిన భారతీయ ప్రమాణాల (IS) శోధన.",
    featPillar2Title: "క్వాలిటీ కంట్రోల్ ఆర్డర్లు (QCOలు)",
    featPillar2Desc: "700+ ఉత్పత్తి వర్గాలలో తప్పనిసరి సర్టిఫికేషన్ కోసం గెజిట్ నోటిఫికేషన్లు మరియు గడువులను ట్రాక్ చేయండి.",
    featPillar3Title: "గుర్తింపు పొందిన టెస్టింగ్ నెట్‌వర్క్",
    featPillar3Desc: "అన్ని భారతీయ రాష్ట్రాలలో NABL-గుర్తింపు పొందిన BIS టెస్టింగ్ & క్యాలిబ్రేషన్ ల్యాబ్‌లను కనుగొనండి.",
    featCatalogTag: "తరచుగా పరిశీలించేవి",
    featCatalogTitle: "ప్రసిద్ధ భారతీయ ప్రమాణాల డైరెక్టరీ",
    featExploreAll: "అన్ని 20,000+ ప్రమాణాలను చూడండి",
    featStat1: "మార్కెట్ ఉత్పత్తి భద్రతా సమ్మతి",
    featStat2: "లబ్ధి పొందిన వ్యాపారాలు & వినియోగదారులు",
    featStat3: "BIS-గుర్తింపు పొందిన ల్యాబ్‌లు",
    featStat4: "నాణ్యతా నియంత్రణ ఆదేశాలు (QCOs)",
    featCtaTitle: "మీ ఉత్పత్తి సమ్మతిని ధృవీకరించడానికి సిద్ధంగా ఉన్నారా?",
    featCtaSub: "మీ డాష్‌బోర్డ్‌ను యాక్సెస్ చేయడానికి, ప్రమాణాలను తనిఖీ చేయడానికి మరియు ధృవీకరణను ట్రాక్ చేయడానికి సైన్ ఇన్ చేయండి.",
    featCtaSignIn: "పోర్టల్‌లోకి సైన్ ఇన్ చేయండి",
    featCtaExplore: "ఏఐ మార్గదర్శకత్వాన్ని అన్వేషించండి",
    aiSearchTag: "భారతీయ ప్రమాణాలు • ధృవీకరించబడిన మూలాలు • నిజమైన సమాధానాలు",
    aiSearchTitle: "భారతీయ ప్రమాణాలను అర్థం చేసుకోండి,",
    aiSearchItalic: "పూర్తి విశ్వాసంతో.",
    aiSearchSub: "భారతీయ ప్రమాణాలు, క్వాలిటీ కంట్రోల్ ఆర్డర్లు, సర్టిఫికేషన్ మరియు ల్యాబ్‌లపై ఖచ్చితమైన సమాచారం ఒకే చోట.",
    aiSearchPlaceholder: "ఉత్పత్తి, ప్రమాణం లేదా అవసరం గురించి ప్రశ్న అడగండి...",
    aiSearchPopularTopics: "ప్రసిద్ధ మార్గదర్శక అంశాలు:",
    catSectionTitle: "వర్గం వారీగా అన్వేషించండి",
    catSectionSub: "అధికారిక ప్రమాణాలు, ఆదేశాలు, టెస్టింగ్ నెట్‌వర్క్‌లు మరియు ధృవీకరణ మార్గాలను బ్రౌజ్ చేయండి.",
    catViewAll: "అన్నీ చూడండి",
    catStdDesc: "తాజా భారతీయ ప్రమాణాలను (IS) శోధించండి మరియు చూడండి.",
    catQcoDesc: "మీ ఉత్పత్తికి వర్తించే నాణ్యత నియంత్రణ ఆదేశాలను కనుగొనండి.",
    catCertDesc: "ISI, CRS, FMCS మరియు మరిన్నింటి గురించి తెలుసుకోండి.",
    catLabDesc: "గుర్తింపు పొందిన టెస్టింగ్ మరియు క్యాలిబ్రేషన్ ల్యాబ్‌లను కనుగొనండి.",
    catDocDesc: "మార్గదర్శకాలు, ఫారాలు, నోటీసులు మరియు సర్క్యులర్లు.",
    footerTagline: "ప్రమాణాలు • సమ్మతి • విశ్వాసం",
    footerMinistry: "వినియోగదారుల వ్యవహారాల శాఖ (DoCA) • వినియోగదారుల వ్యవహారాలు, ఆహార & ప్రజా పంపిణీ మంత్రిత్వ శాఖ",
    footerCopyright: "© 2026 మానక్ సారథి • జాతీయ నాణ్యత మౌలిక సదుపాయాల కోసం నిర్మించబడింది.",
    footerLinkStandards: "ప్రమాణాల డైరెక్టరీ",
    footerLinkAlerts: "గెజిట్ హెచ్చరికలు",
    footerLinkLabs: "పరీక్షా ప్రయోగశాలలు",
    footerLinkAssistant: "ఏఐ మార్గదర్శకత్వం",
  }
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, fallback?: string) => string;
  languages: LanguageOption[];
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string, fallback?: string) => fallback || key,
  languages: SUPPORTED_LANGUAGES,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>("en");

  useEffect(() => {
    try {
      const saved = localStorage.getItem("manak_saarthi_lang") as LanguageCode | null;
      if (saved && SUPPORTED_LANGUAGES.some((l) => l.code === saved)) {
        setLanguageState(saved);
      }
    } catch {
      // LocalStorage unavailable in SSR
    }
  }, []);

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    try {
      localStorage.setItem("manak_saarthi_lang", lang);
    } catch {
      // Ignore
    }
  };

  const t = (key: string, fallback?: string): string => {
    const dict = DICTIONARY[language] || DICTIONARY.en;
    return dict[key] || DICTIONARY.en[key] || fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages: SUPPORTED_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
